apiVersion: v1
kind: Namespace
metadata:
  name: signal

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: signal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: bbernhard/signal-cli-rest-api:0.97
        imagePullPolicy: Always
        env:
        - name: SIGNAL_CLI_CONFIG_DIR
          value: /signal
        - name: LOG_LEVEL
          value: debug
        - name: MODE
          value: json-rpc
        - name: JSON_RPC_IGNORE_ATTACHMENTS
          value: "true"
        - name: JSON_RPC_IGNORE_STORIES
          value: "true"
        - name: JSON_RPC_TRUST_NEW_IDENTITIES
          value: always
        ports:
        - name: api
          containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /signal
        livenessProbe:
          httpGet:
            path: /v1/health
            port: api
        readinessProbe:
          httpGet:
            path: /v1/health
            port: api
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: api

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: api
#   namespace: signal
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   csi:
#     driver: csi.proxmox.sinextra.dev
#     fsType: ext4
#     volumeAttributes:
#       storage: data
#     # volumeHandle: antoinette/pve1/data/vm-9999-pvc-51bfb16b-c006-4a14-8e5d-cca4c8a78fea
#   storageClassName: proxmox

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api
  namespace: signal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: proxmox
  # volumeName: api

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: signal
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - name: api
    port: 80
    targetPort: api

