apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: nfs-subdir-external-provisioner
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.18"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
      interval: 5m
  values:
    nfs:
      server: 192.168.2.6
      path: /red/k
