---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin
  namespace: harbor
spec:
  encryptedData:
    adminPassword: AgC1RiTToRi73HNFcWdJjJvxml8cI0ZB8Aap/MT+vgl6Q1o+dpqFgGvvI4CnG/c4oP9ckqRFIj5RD+EYaU1hBJs3ebCqY0B7nL1BcygLcuQ3BNsTTVkAi5xvm7BC4heyHWI75H/6v94yIBnQB0zHNUAoOUhGEmzKsRWQfObMqFZWYDOwsSCKSYtPd9zdTlvsHxCy+MgNmboFdu4ZexmqeU4NHnrBk/eIDWJ3Tget7fd7tSrxMn4xr2MGRbf/3bHMrs4m1E5PHYnrh3Ye8F+eqOdWUSDAzt5TF3PBoNgqKi+KmaQd0v/Kdgorcl/TNK63u2BnXaF2t5qFKqljYWwU+sH8UCTN6bmnBDlp8cz3ul9H7yqodLTBk6mHfZpaoUVKtMcQL/8KLzJq4UvUBOhzOCjFLskTWhdkaktDP8Q+3nEWtnzosOzAjRzbntwPgrfcXQXdrydbLWwBOkV3Z9gwpoleqQnesJIGc6hjk5tyF4oPOzdE0GslmkcAlXYbo8ntcpjxeb09LM4JebsThoHLNEBNuB1qeV6tmE4ZO8DHQM7Gg0ZIkHSHTKAK+iLFICohWTO/Cz6ke8cngKo/0TXMAC6NuvZkA2fV4Aesl3dzHDL8pgeBdoy/poB9MjKa2tkppM1H47JRcW8gGkwfG/KEF6Vwad1Eqy4vOWUEZHMMKxsQJToHP9McxTeWRdba2ZicxI6XcI8ZxdriEw==
  template:
    metadata:
      name: harbor-admin
      namespace: harbor
    type: Opaque
