---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buildapcsales-env
  namespace: reddit-alerts
  labels:
    app: buildapcsales
data:
  SUBREDDIT: "buildapcsales"
  DB: "/db/buildapcsales.json"
  POST_TEXT: "dualup;Terramaster;n100"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildapcsales
  namespace: reddit-alerts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildapcsales
  template:
    metadata:
      labels:
        app: buildapcsales
    spec:
      containers:
      - name: buildapcsales
        image: ghcr.io/rssnyder/discord-reddit-posts:0.0.1-beta.4
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: buildapcsales-env
        env:
        - name: PUSHOVER_APP
          valueFrom:
            secretKeyRef:
              name: pushover
              key: app
        - name: PUSHOVER_USER
          valueFrom:
            secretKeyRef:
              name: pushover
              key: user
        volumeMounts:
        - name: db
          mountPath: /db
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: reddit-alerts
