---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCk0Xt0Id7d/IIdU67ubejKJCciyTCje+K8N9/SbScae03hSbaLb+GEC2HwHo5+WoIYOBqxcxn/ZuOi7zY1s23+jKRwg+nETXmtXDQBXacpCErurnbqpio2AXIfdVUkq05fAV98VLojeNv3CI2og4YZ2Go9srCD53AQP5naARFzCs1uB5pa4eEAsXSTDGq2m+/msCLYe6T9yVy/V4pDthwZtv5TbuARcTECk0f8Defk/7OYhPcr5LTldwxjtbqGlVnvP4dTf6RWyonFtx2/sXa2XcJy6wI772ThsRSeWQxhhPSyuueiLK67wARRU0jJ1Z5DgMBFlI1S77z+jDrpQTor8GOYb/WS6ch0ngkLYLA+rZ/lf9Xjd4M2XpsBJSfixQ5cWSs+gbreI4QlBJJVTJNe7CZt5Ln8J8zgIHrOdphu6oaw+/4IFgQ9fJoJ3oBRaDIF3T+pHF3OvzFuFN36XhqwW7SKpyb2Ng4v8F98rX+PZDwEC1Au+yvuRAavQ+sS5Xqqle7NbfaC2Y1qGAOkDiYIhXCKGZ9m4fA+4ry1YXNZLR7RvJNG8STXszl1qM3HT6pmvn6vB82bCMICv+qII7eeBdyddQhBhGnoc49m3YRFP7OCW3ToJUhgj3/N8J6Grkkx/bwoMBdtGWOedyIyHPT0RO+0zGSUUoMJcvwmEjEJvBDvB+/H+VCq9SrNl2kgFyDkhN7DetX74g==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAbTG6i+lw9q27576xjVpKlRWNHGIg5JSRx8kCAIHzGR/yCSR4bbPW+LPpb7bz5V/wM2XgzbX1Zb96In9BOu+9b8PnZyzyoJLz29STN8UJlR3QC5VH87APsYTuBHaz4FN0krvpmRbG0TfJ8s9MztKGG+GdE8MMnmFjo0x8YiNrKPCBbq/Coj8yRXDUG8atrHz9rRRJ2k9E3YRglj1mv3HnlmnEw9nGd+IxaUdXmaBDldfKToHKkWsziFvdS72Wq5QcSJ6QRmzrUy24YgqKL2sbjYRvzETgEOLCyforbTkfADbTpZCFPUlMFQIDWeuIRA//DQU1mdKU5XMwpZunVel48DUxdcYszYiLV5Qh3v2/rQ/LeuqL0SHsx2HxHQK46MwfyXX2NLCnqSYaVYVmNO0MhThSUhQirOoze8Ut7UcuPJgcdyV1TDHZzR7RM/WSX13GHmN+OV5bvOCvAhZ594P9LUPo8uPB0v5aBQrSQ2fT0msxai9MOXowBzHvwvxSIXM7/8jULmD2ov1U/wNBSCF+YVbLROlN4tf7KweOM+BIfMHLCEjSH7LTmdAtBqJ6WCFdaQWYva4MvNau2E3xHIsxCxWJdrZvOMl2samJlVz8pyT1wgvnFZpFrJI1JpFsF3bwzccotOk9B1Eo7kugl3WkbP/nz2gyNFHtRmZkDr3DJkffqKERwBiISIR3Gm6Q+QfihA9SacDw2LjY=
    AWS_ENDPOINTS: AgBZUdYZ0COgkh0d0lo3t78mZzGWcO98sV3hIDvhyjiTA9LKw+L3A9QQeyhtIz8okLZA2oIHIffxsRRiLZFc+NCewH0rdZeOSJPHkP6vEj68rAqwyUf+IWlRHS6oaQx1VZ/Gh56BGJNxRKAIO5cK5zHEu7Nw7O0+UuVoFS6vfhpkogI5STDbz5TKWYRUdEG3mrX8e9P9omJ5mCFDsrBjp4MphCcEuYQsVdhZVewZ5IvQR7tNFMzeNCDF7t6WjQrheqnMqd6nExAJsjpvqkApPOMLnlDzVKxq/13O9I3pWkUip2RhMm7e9gDAjVtHVyAhhtlMq/HHwc56zsMs4QZ6J0UloRo6Bd4UKAw+Gxr3bB9Oph1BI7VsN3MboxPka7GDZIelZl8jAo8UQPpeCTqZmZQu6uJJjEn67j24wxkbsGAsnrFJURkso25qYfdp2w+Srv2dl5pmKRxNe7Fj2Jqa4StETCPFhYL/f1Tn/g+Pw7Nd7bvjH+BxNP25HyaczkT9S4nuP+MbpcqvUsn8R5bwnfefrFZ6ijeBJg4wA+rxkS3AVBnS2i4vzWx+yj7W5PlHCL0aCdHu5i4XhwCb3DYpCyUMd0dlhrT5chzg8vpDapi8489Z3D76LtOHB865aTIKMwl9jmtnl9lRaBynkYlXIfy+dLD1gbAa4CBLPlBvxziRijhhT7qtYj6FLfokwettLH/Z1IeDGqjlt+JZgEhhgNWmWsArilHXI5HtXA==
    AWS_SECRET_ACCESS_KEY: AgCdKEO7O4EU8gW5LjwmcnrNEaxJZe7UvDzjaWC3G3kp3tpogdafNIRTKuf0u9R55buS0mjr91SLyBJ0z/1DrItY9JCjcvRQ31UGVVg71qHofjIYIShufXPHAKrLDdlLxhraL4KwCAZr6N2Ua3eHKSTPCooAGMeapNvjs8ghMH5Q5xZ0I9RqUCWw0lOKCdePTbm8EhX2BSyk6PaGHSpsvU9MBXhxuj+qxs/iQZ0TwhXsRATDzIiVzg/fykwNCe8Hs2LeTQPVFwi9KIlYygUnSfDJQsi5zr8I+lDb2RBaLWCz9SG9rUcfpLQuKgZ+hULn3Tv9TqbIyx/vsSEgcez9TdwUCjM67c/NOCkFS3wcZx0QMbnoU+rQqC3zDKa6KifktneDZAdqpc2/ncZrRa1nYuLqAtA6OmoifgUxBfuom2jdUP3f4krGsDXDZApcnysqzzqskztnczderTiGu7F1hCT6G3qlnGEnYd3GuQKlse1/q7U/dKDYZQugCXQ1ZfSXnN/ulsZT7lhdA90IL+/SzAbQaxfQRS1PgClgQXDO95rfsVSPmbFUPmIPRxDP+Xm+zUEa3fuKpPelZiHBJokjWepJTS9/cxyOtsNsuCXEI2JBxLQH+K0daP/LS3qrsfDS0jz/j7JX5xGI/wJWlguF8/FieMOAoxmPiu7WRoeO2gck7FsuvdDZsQRXwizdhQ9YM7WrWjzNj+L6BVeBgvuNVzN2dju7sAryOF2Hn+Kdzx5ppL3pwj08sOAf
  template:
    metadata:
      name: minio
      namespace: longhorn-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgC62/JertCrrRZ1pKHCjHEq8C8Zbgi3/A3rseqMwAE22PzzhirWBbNOhE6kiggyErizVRN9CgkpFr8yXbFx2TWDvG2RCDH8u4j7OJYTLhnfwV4PQDVSTvRBMYq8OItTCum+QPlWw4+8x1pRqTkowd8UtHJy1ciWXXMxaD25TMQwoxcJREpIlGt/Y4sVNvZ7MdwpWR9yk8bjwoBFkJe+e/RpZhdMTtsUUhVu2Uk+7dogXlYsBQo1ul/6Z8Jr/XNuqB/SpJAhzOuKLAmAqxO+w/7MnvNxVUcx9vgI+7Xaah4hpQMGcF/Ity1907trrp15fZQXGhcW52VKXYUgz/9+ngYRrlqwQ2hAufTLhLHeyvYdkuppvpVEL25cd35CsD3Apyxh2/iPPKQ8KuN/IOJIwW6ZCa5cSeE9g+mCbvr9LOJZbKn2mHWO/rKFz7Ya6jYAG6iD5nDxT7uFrCfN5JHXQFmnPbrWpVYAiXi66NG2QCROggtf+BrM1hB8yFUeL66uKA5q5qpTp1EgaHk2X5sRq22/Zj2c7bP0MVrT6LMJaXvi3WQsvZCkYLMA4j9Wzy9Pw6W39hgvPI7G3eHz1xES0RJAYuAfulxioD17Ld92yHxFvmfff4cx4jGoCeQpWuygfNtOy6XQEX/4Xwy7ilRwGC+SnnAhEa507zUPyno/gWoX4k7kXUCdd/3oXzVn99+uDtbGdpQOXyeFSAzCpt4o8zyeKQ==
    client_secret: AgCoJJxgLpLWtdMfRo0aKXW5AQlKsGCqia7lq2x278DwUBKSSCajvFtBvfatxGFQJfgcuNu/lE0H8UKmGzWZVd1IDraJ2JzIjRcS1JECT+y3TD0UaFIj737OPmfZ/MuwPWhEgo+f7fGqicOfpfNQhah2HreddK6Iqu17Pa0gbDPDZId0FDPtig5u/Z/Loa3M9VcMEWN3j3LHYBUnHRqmj7FyE6EndJ4VO8uc+KJ4LoywkXy+++SVwzxWfu2UV0Vzbmgdkjhd3OBk042+aqVMz+Ai7ztn4BYxHsd2VoCMkDfHWCYNAi3FAtRuuYboKVEQio7IUvuRdUHvx1d4eZAHLCkKmh+CaWUfvB+HPUAqCBFOy+xCsL20TmqmaM4B72hEHm7Nqd/2PzogVmkAaNCwG9aSCSRjqntbEuRoJZBanPyk+QBfAMFRU5IZevbDXqFbxRhVVUaXZFfq8bSfrrHMilF2XOpMiba54oqHyXn/I8JYHn2gFAZa84vtUOJPR4rHxWhFv+SyvhEP3xRUSUEOCn8x14Cc/JYZ7TClyvE2gOmKeJimDXU85wIRqHsgmyOo5S6doOZMoKueh0xVCZRRoIs1v+oKltyyuVNzf7ROCXty4GhyCMOm+zsTQdBbEXRGzuhNPHw7utGPS/Le1igOT1W16apVANzUOEbgJ186dWOj9WFp1LmeTGs5gTRYBHcQDwKS78c8eQtIaoxNuTM4k9zStlKnhXV8gcloYUzRaC1r4AkTaNHGwihOUd5Q5GneKTpzsH6eFBElopkBKJxU/mo=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgDDrkzcOO1XCzFkRTV6zg2E1a6KZMBjYSsWT6azZlt6PbvIptaRDUJ2rrYarFGs6+tGMkERG9zFuFgnzUDX614gAaiuQp5Bx+yefjc+RHvLJJ3NQoqF30xIkJY6UqvFJcu1J5b2JHKfI/e9UjGqoNxjfC1a5WXixGLpnJ1moJqINzErSJ3CLuoxndzHzGPO8IYjhb58POyI6efC1udJ3QXPWZLsZEhtZLyyikn9UulapqwrMqAWyAlHZ7MPQ3P8qYhfeC9ludfQTbo43TtQlO7ksHhDWoFFxxorAPirERNV2O571FXohEigNRuhoBJEid2IpJaBRNGFtg4nbr1U7QphdQAPR092GO3DN2oyFP2CXK3hH09xzrY4jeTzz3mwwZIeOpDaMjDwBXWANMqtnyedyFXKHnoAzn6dykGVr/I5jqy5NLYtgS5OjEV9EXppiUSYGniDlLmIpHBMUdPxJNJ8ZyInUIoLhrBBabQVbNS2x6K8kMo+mEiLjL7HBBDizvmpAZ1+iiu+AVcqHGq1wl/GUqYUkP8ibZBWPg8R5D6RIMHaw6xAbVBfSh6Rg/Uqck9qPLn5qnO4hkHtc7JBxc9JpmJQIqbIAH5OGUAkANXY4uMR3oqFCdASGnmR03PYfUn6YFiY5R0nQoru5kNmr8jhudrW19GH777BhhdBAne3iojrB7WjnWJakDq7ljKL0AjJZcO8WYhwW44Z7bvi74W/MGpx7x2cg8vD+7CTKMJV65gu2jEaVpwd4t/4cg==
  template:
    metadata:
      name: delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: work-delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgDNgfTvwSCDVmMG1bw2Ixy4wzhpplOpVJ0waLBaka1HO1yYWx0pMQWEODSqBuu0haXTa/ueULhRKQ+BGQmulYHTQSksEA4CqiXJF0c65RcbGEljacxle/rSZRvl+SBq9LSNZFa0/1cCckgLSn3+qykzw4iZUK5/Ijn+V8gtXZ31bskPj4z/WbKcE7QNlQwyRml8TtJoiisPMk6Md29ptpgBnQPASIA1TTQKZyIGk4d4UXbpT1TzvYNv40qy4V238oF/7owZKq9pMUF2N8O0wj0mRqksJ4sofXU6pXucJXHLTlqxnfeik8abhAjsTlK97jsQ7Py/yocRhAAznbXgm1T7l7lq/VJPNF86L10Y5gpQqo08A9vLcEjyViZZKmxrWhPmW86NfT50MjEhq6x4ziUJvguAWhFrgrXgEp/xvD9pF3HCFbxZOeWRqX4yUXQb/NtOhdVc1dy770+LFe84Fopsqx6X+9KK87O4IdqxCmvcLiSCTzaLftSbmp5/5PO79GZeX92GyM5q42MX08Exu6QFEtqceWwz1tuWkVaAArj+rwTGQs4laYa95NrbMuXyPiWomMnn2UD3PF0X4NNJFiFzFMdUfhWsF5aVjuzUHkBplbaAHMI8gSUVvSFeg5H+o5qcEKo7oqwEEEap30tFYuDNgCZI65wQmCTfo7jR6xkx2UCt4i/N4lUp2lNBFWGTP/LqToqKMStjHtaFmiOgzegFaEN4NfFl4SHR1T8A0f92vkPkavZn7zojrJpgMA==
  template:
    metadata:
      name: work-delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
spec:
  encryptedData:
    pgpassword: AgCa/e1uOIdEF6z2PpiGe51Zhg/Cz6FG/XKIINg9AVGlwgd7TZvEnmSSyvyR186bKJavd1IW+JHJ54ZPIdAbFXRN/53eriNWiH8erzPJEYI/0jV7kgPzpFIFIjrbZswFY5KpeGjdm5Y2cGWeYiHwQcqkxflhqwbCp2NDaqcJxKPXxnxzrMyKEJ9770pJADses36KDLmwsr2hbCsm5t/RwgVf5TrR8BmUhWSLPv7kMXv28Zn0jzqzZX3bWcUsHfryR+NLcVCCkct3uybkEhwIC4Gs2yVd3ky6ewy+jIFpGaa67elOjJdmQUOgUWByWTAtuthnyE0yZIPqcaogaQ4euBLjruU+PwYuF3IMgCwkZpnB4ze2XkC1qIsr6vT9PtzzE6SSqyhzOzfjREq6OI+QG3wlz+RnBaTTnwO+8QbeoQwcq0qPqc5f1mXzIuixdh+Psvjl/Ni+5u5Y8wg9LaxNoAGmEosg0IXrgiF3iyjUn28u+Dmtc9uNJP68w0JXRN3hyTa5InfG5TkDVlNsNQKDw/kx9ZJdxd6PbFxth9FBepfh3kN2MRbntQTwgG7mU2my0qtas/xlQokfUHmCpUOFdk4ls1ZToS55zb3xir5PGuIxojiDi+iJOMwPlbKY1KaqJGI9ArZVmBxNh29tKeUAY2ZmMG4d4QNzPdoBABbu8Kuonz2ASnc+PwwYlI/lYj36uv3eqqa836Ux/BMHWKObdecndryh0eoHoOGQ+OxygXFEUt0mbs+GvZm9
    tautullipassword: AgC3chlQZlAgjNlSjjlBjJa1uhkEqZ2bzHuzWdNKvmHUV5J+Prjhgo59RJy9e3AvkfbPVlhAME9ITzUmEhPWS0uB/XsFHZ9DjYJXpHh/3uyBe5tXkTYFZdDHh31gpT4TChWHzuzPBJHvpPazWWh/mitgKAZ156yl0pGyngfIGSuAguDht3q1CY6MSM1i4SgF+mH39NVlkU9EVYePN8bUahDRfqk4QJjM6IHvDwM6gen9T9NkgRsRd+q97oj0JipZY0wnkWv6WA+eV0/Di9u15oIkNxtwS9YFk78sbldAdLF/fI0OAwqbwrXvGvxjlr1u5esGPQn/IYosSqy2kg5gxEDISiQHqz62Y09sVFYmm5zfYB9qUZunwIHLjSaFtUGtaBqffKHvMoZnx2iMXwKff0gjA7SZPGviXOjdOdJXB9gk451GXntZHIA4VRm3eByibc9Ky4aMJA25/6jD1ojcbs8sIJRKixDJK7pqip+/7PhDNyLEeF/uJiEEbFtMvwJnFKxsHRGvM/hLFRBasOjwNF8ZkjgR61UPLBgWKwh73Ouj5VmPE7so8K/YpHNbWZ7ApjJrq8p9hVxOLD/g9kHsN4xNawoFNBxH5LZDUkxZHrliymlTNa259sukfjdar6+XixLRrGH5ioC/e611PO6mmyMoZBfgwhoNwtwBgGY5VGqTDRsIrX6BgP6+X5BRrcjBM7vYvyRspmM+NfVPd28SgdcXzjr1kUdtcShJLZAIjFjQXg==
  template:
    metadata:
      name: survivor-tracker
      namespace: survivor-tracker
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgCL/U8kCN5khHEOf7O7nAzC1lxq7A9oB96i0BAFzSrFQ0cqBbAfg3Dvns9edWI06PWr/QR74qdGdLRrSZYvUPZkQG66TCIpk0tmZIftFs97HHgmefGPdEuiWVPshobHv4hOGImGqnXrlJ9WLJqqFSsV4QZ1XvNpKveHCwv65w68RPbEUsmLIjcnef68p/N6MLbel8rvDL/OoiHPB3fUjjxTbPJNx3JHgsuedPMFKq4SvIteBBmpeqFmdfwXVPWtF3Bwl89JQvWZ6OWl7iXr/S7w3LXyhnxegm0e4qcPYStAT/W0HGRRfbH7N2zQRsb7aJsEFp8VmWu7PkBlrfkH3uNaer8eOuADZIqJXzFigiR2bhIQ/kEe72Sj8sxpSW8EpwGC1za/Ij0fF3E2rEBOoUGJJpCCkaTyPXHANbusuUOoENKx7G635GqxHiaYrYkuLsG31FqDugMfH6NZoXjQwcyn/1hM39S0NuPRhaljjcOV1SwhTaicpE4bqlKLp2ivNOssfBmxayY6aAP6/bqsdpX3oDrRBtyxBxwLvXhw7kZNOzDviXt/3avMtaxGeIvRjndtozZUEGbUVvsYqk/CItzae8tsYxzY0oTKM7FeKazSqp7wYpqY2R3L7SRVX2R+bnEwGPQHJFJIJ1mkMxXDwTvM8Nh33X/I5cFFcqDJSA33ITgRCAJ15j6u5MjkfB161g/OFz12uAJhRDSGjANZw8bt8LnO6KaG6NwJBnonIOevVvkmNVrMCgyLCc8wh1NyIPueJL7ezFylymxgCFxto7whyWQW/XxTvrGuBgqiRItrdB4zjC5tx5RcwV3D8P6N4h6E0hNKklvlEvdFVn4IK7MRfW2rbdu0A5LzSRTHPP9W3SBzg/Obk9UKOk1m9ZegzzZWqTATRyK8F88gWwwvj/8h9j9mzt8l9kPhNLP0FQK803h/8A==
  template:
    metadata:
      name: proxmox-cloud-controller-manager
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCvAuLJzf4CX6LBiQd1PnFZfF979RVJ8oDkvLrnZSn3x+dAuU6BqSM4A/MNQVyNRsx3bSF0vpxWZYnGrHyG63sf+X7EuLzru491jBv9/EMhHgeitmbWGz7NXkmyk/66ojsiorgjqUWKZM0fSzOTyZizQtm1DtSXXwS4Bs8T2UrWkHj/aIM5ZqS79BgiKLPp7Im6XiQa3hKh4tyGFTjrWuDCR8WrS+MCOZjBtNScgnwjLkThSZBOKk5//MJXTYFJhPzdABawMCRtCUet2NynKONkqUaFs2wMfo21Og3mCIxQQx+3iWED6F6yzADIRtROCulUvupIpMkBE6tBgeLC4k8v7HxjxttcXn/i+HOghTwqpUiMsm7e3qO/uZsU2TMfb8RPmtKlJ7yPmGdcoI2+1tAcZkwrDnlLiLuoTMfJKU6bPeoiHrJYVyrl7Ecf+sg2mg74zWFUQXjYME6r9W4/44LZpoD4LOtGS5OUxMgM0q+lUyukrns8KaaWUQy4iOSY1rdOsUgRd5OQo4XHvl+eniUdFyGOED5LxoS5rxcJk+Q1HITziU9keAIqvMhbFsNBKtOD04dFLkwT9uWx6XeahJDpRSVTgo52IsUHiPehV8Nk89alNedxUxuyU9Fne4zT41QJR1zZrtKubAEsLklJWkd00gALAvHa0AezRVSQO8cuijQA52/dzQXGZvgOlTgLdBhhLQfdSjr6drorawSpgJ7qRXGMJWBkwmIFP6hMwGQQllveweqxIZ25niHj12lOzaa9Q25WFkf2Z5jZlJTZwMqdPWXl4MTr7A8DRCvtqzBvxS4ZgZPOWE30U7DSsvPuTH1JxxJC9JEDTudYM23xe1Ov8eC8Krfn9LNQMRccjBiWQTWoePlRkxPhBMGZW6Rhs2Ry/dvrWC8AzZ4bYauvd5Nj0MsoU9mHR/VniDgF7rBL32XJ7l98rIQ=
  template:
    metadata:
      name: proxmox-csi
      namespace: csi-proxmox
    type: Opaque
