---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCKKwRvAtLJNzpJKmzDeYTXnl7+uUlghUdGGzxqQ3933gez23HGxFgrhg+tXIMQthTn7mPp5P9zix/XO5IO5bt1xwCwZRgSGg1ZDE2Va6ANMhN1MDYNKO0MqImZt/C1i0reXAFVc3v47OVVANKZcBE13qwfeRnCRsmwzx759I9FpGh16stOAuK7ev+/dSTYPjwx5ZzuN1ycIWmRlrBXWhxcR+DE81LYOcJwCTvfL6xoz0lt9K7LebxXEm0n6Lxagc2de0WQ4r3M7v96NBbnhQ4ydjIB1RALXJCGZzTuC6i8fXNML7317eff2yipbLxUNVDNafaB1tPC4Or0tB64QIgFddCwbwmhxPn+77dkoE0RIlw3GAgyUlTpwgdYjlgiiSFeRGIB+2AGtjWLyYpkXhzh485+6jxYXyI9rxEf0KaoZ025zDK1EWiqS+Tn+/jTuYMdQ6e+BLqGxJrEzIVnQB9mpPudixgZutzd/fRExxwDJInx96Dg8ksNM5e+otStqnxjm9+krYBvgclC71EoxmeTx7xk91ZCS3XhE11CpPWynCnHF2IGkmqgjmtGlLslXGvk5qo4z5lXBXfEv/CRZpyPsWVaDQIWPlICF9nmGwdJHTSPmvOD20kH+v+n5m85DwwbrbFFEI+qDqC81RPK8DtnDJvROWwBegqw6D+JzeeKL4hpnfx2CejXL4hNGAInbb/219Xs38VkOw==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBc2yOucgb1YZSbajVpahLfeKxY392sf28hpOlLAZHYPvADXgy44dkI9oc8QHrUq7lhAbJADZ4u3HCthlsB3ZMD4749NReWY2H21nUiRzLtXFbE4zXjxLAmGGqAv1s0sfN1y0fEECjuAj0BKSVZWT13SG0XBtuiXRgHwc5jZWpYxDlnIX8qhSdU+ZdNDhCofGDOH14byh7H3UIuA5WpvcVDdAIRawojMtksavpOPJ5oQf8VS1nqbCFI024JMKIrgvK9PyEu0GGzJKzl5F0aQXtOM4YuPgGhBTU082g0mkBVOtzAeOIAT0bNH3KCI0vjZcshUeXY6gfgL6+pb4jDVzk3NxouDlZos5Vfl3Kp138AGKMbYRmpvXl/qUFRns7fIzFqlQyNAaOpOTXuhHI4vAOqxkbe1uvQbx7OLR7k6TzoZH7dZsaqsC484tQFByNFEBL3kGMOthJgkohpxlO2J3Lj/uRMowGn5TJyYvS8cl+NYjmqPYltmTdefs9Qiug/r1w9z2v5RpR9JKMW0XZXPUAaLKsJbf7ket/0YmasLOHfR4lXZDVQqA4pM5hr7qoXSY+Y3sqeaIcopGyzpkc3XZoFFsQkdO+tKuaH8ZXtJg2HTHVi7YuekSohlTm8gkjuA2rXLIGYWm7hIQAob9m0FtJsjazw1nfV5/L+NGPncQisxb1vC0SAnPxmRysfK5qiMBe0WpBnkr1gHA8=
    AWS_ENDPOINTS: AgAO63/ZPMP7z1G9zpskg7hdk3upyATmzqHSlsPNouqhdrCFA/Nk+1CeQVdZfn5p6aEb7X6YqoXES0l2pUu3Slrk0MsCWxq+4tm0GMOVggSBCnN5jrCilWhlxFfCMKq5qC4qyAQCGG3GccDnkNmULngZooVlfjf+6UlvGtAiT/kvMJrf87Vcdo0h23JFkeXuNJCTkgpm00jkAmGpxYMAwKNOku0YN5hqYOZYU5sPBpqtzcpqGRelWSkbg62II8vSrE8NJ/O958o2Vunx0d2QdajOMBcLsIOxbMklo/xoHdi+9cUMT/volsmLQ5YzkXqDp+82xfviqMaO1/Tq3dMZZdqfEMERIlBghVZqyk2xtXx+zjS9PxFLKlXatEMEXY45Jfzh+GTmPso/r1plGGfcQ26t8GlpMIVTx2vh7yA7YRF7OyZeWS2JzAh0h4MCLEBXrhTJoWAJyaRJbImf0kg7JKD091pZAZSikHfDJ1aON43bASGKEqx2L8WYBCRuV+f6axVSCilMj8Jf97Ifb7s3DAYcRt/Hxejfbb680/229laZwrsPcCbd05m/mrcT3doY00ApiVsjomJvo6qwK7arnPJOnU4v1os19h3SVQwomodYvRtKo2EhGmiF8EHJAfsZmdn8CEmKU3h2hpzhTCGNFobDHy6QmFsXxUTxtGlfftVtP8g1Qip2oCqFiAdp1HQv+/x5uI5dE0dDweef+ZXtawocjq+IT0pA1gnMJA==
    AWS_SECRET_ACCESS_KEY: AgABeZjLDxuDBrLCMdfAMHZWh3qtzbuG6pBDr4jH+1sNVJ0Vg/2ATrn+QFwDH7bP+Ke6tSH6ar7r7uOSjhVtCewtJhtFNrepm1LBm9NyzY41QRz9ITS764JV+fqFtiXLqn0j+aLaDQaSyi8+UmauEZCTJ5QmTVgpKrtCA45zerJmGrM5R3JzgOjdrQv7SIF1QdLRI7ZvaLTOz+w3+oXbToOfdF9c2I+13nUK99Ux1/8TnaMpQ6jaFfIfzJ1naaAt4hu+k2ofLFvbnLppVyM2WrRhU5geYxXBgr0pC6jNTQAMjxflGDX5i/tOkwj1qaRs3/z3AyoMEOiHVkoMbyuKrhmB9SnNyqIEGCcPAxeUOLfJndPUnGvNj+D2GbQq5HnAyjAeLj6qtmIuqCabREFNavkE3um2TEEzx663hcHOCl6RiJkOnTYU4Nseq2Lsrm7cy+Aed7r4LH+uDuPXmtyoPD5eyBaE0XVAwXCay/u+y+UGPT3X6wrme4w07MEhzuHmHp3nBL4wlfm8EWFLWS2KkNsxlkXyVl8EN9DnGj/vfM4BsDcnwqMDmpyFLp5sIVTeA6gaq7PflR4X5R0ogE5UAGXkjChTHxSeVKUELwRjRjN3lsOeW1qwlnV4O7ue5u0k1mcCspGWmeUlyAzJybqexUOGOJTZMKmRFSMrMO//5/VastuBh93ijrLxcTbPuGquTAiZ4AomjK6ZO+UW2kuaSOHPf7UD2amRMrkZ7bxxZeEcJZP1lnQXJp1f
  template:
    metadata:
      name: minio
      namespace: longhorn-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCZaNK8o3Ytp998kagRC6r/hsly2VZaAa8vzVT9nm3H1NmjTrYJlbV27zsbP2PBq/E/VclqB7rM/frB0bqbMtyY5EyvvOhMQ05u25Njmer5ILSFe6IFLjtxy7gbQt+8ohy7/sVRssNjVYgtdWSQ13Qj3A/i4x/BrMe1ErFhF+U1D4zYI4AKm+iiY8Kuyb/tlU6W/mKnkYMyEMENEcZWiifEltuFjkHygydOwaLKBPci4vc77qZP9QosKh8WDa96vLplJAyXSmrkZdmUjBgaqPqo92q2HlLluqRNlol+cZGW+4tLMNR7vu8nrf2Cm3AiNLPZegdONR7aLUKlIX4oGKi5ntnHHwEU4Ilui1dhlvvXzBr7Rxvqo+uXDhhjSVR3t89sKqHYd+CmJD+SE9rKSrFq1Aa5GqjApBU+CUra2cu4MaE/Bh1ByyaE1abwyI5lMRIr5kZLR0lo2oNKoQeiu8xpGeHzBHVvFPeSkKs2X74IxvLFCyuNWJR0PuyEsWZ0QItNgUTo0+oJ/d/nylDUJ3DxyU4SmSgOsB0ZG9up3gyDMGC1qsdUdeM56qHx/Qe3PPoOV+qNWmUbPg5cgYD4OOXMz8LwRVvvLlUiT7KYHyuM4clNVpfTPkIe33HieIrAGjirh8eJxq2zV+3+WMCHJHUyDgozUivimAk09EUHsTZonNBADa/gIqAg3B1pVMM6M1c11O8CI6Aq5RFxRZxBYJIFIQ==
    client_secret: AgBav9wxz9ocu2xjS4vtcTBK/ip7i18tmHRdjWjFPu0hgh/n4sOghMZvgP49KIh8WLceJcukU7ereivK9WeXVJY1OLWcTTWqT41i+5+sSELSL1E/lHr0PX8+rW3REzDFFn6f9G2HZ9SvxUfvcTcBQFH0TH41EeOatiHvhBzxZ4JQO7XAOxYQYV56HaTKW9BD8IcA76S7zzh1FBH4VeyOCwjrW/B9WzHfHR3+YHS0HagVa57QW9KqqBHTAv/H0nx2pXZ5FKKEbquoRFYjkMOT4VWqv0hll8xpqdRjoTJbr+2EMT2fA4WTdy0il+PERyNWwLcdqil6nLTmzbkG6OS3pUoHusO1IeSHaMZ5lLmuZwfYgfc8fYxTCIA94hCOmT4nuOj87zd/GM8gsOjsOxqhSNAehwCCVvqZgwrv0LviJ1MpFouFWF57uFUYQGRd7T+pKNZEveJ4ifEnL+QtLzdM4xCE27ZXnIBsR2utTy81todAwmsinYdzHjkZZ5mPkIpQ8zlVxTViU8zosyMwskz8w2h+hmXcxQB3rFvjX/b0Fll44JH4of8puJpmlMy4/9jDAZeoLpT8VIjNdeRko8YxQmj4WuAEzTQmmIGPgY6PacbKsH4mOsMnjLgS2ca6SXZtAdDZJfl8Ca5L6SvAyI+UFhnHyJTrpeRhBJxQnR1dqYXP1Yi34/hW8NwwHol2UcD6qFxf6An9UKbJ3+owa6UEeRQ2oxsdaOcJrjV0I1QPwqTeNa75O32Arm757tU7FuSh3S+1txmsthMY1u/3IKqye5s=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgBQx41uCXWBztWw2M41rQ+wTPIInHe/JDSBqdomJBBHSISIajPEG6ICaeyiEqP1ninHB/HYj28b6pMBZSuDIM7sBvdGASICdTDbvBMrtR2NGLsbwG1ixXVmr208MJXdoqnm6M11Yu1Yyii4jd5Qxok9AvuWbl1CfKM2W8MnR2t031/bh7vqPg0aj+vJ0xqME1DDDSAPI4KHQMY0l9BrCFgCKNv4ofBeZbL2m4JughpViyoO0Bp3WzL6EgsP1rS2HkMICEt4POHXjerRFli6bLtDilLUTI1xfv0NZeeOA+jry69VuGhM56/IqV3iSJgqnmTv3G4wNtprsQcPfZMDy4JHfPRuXnXpfDbFotvfWnzHMGdWNENfOEb1h8f0ULepEYrxsug43B1YRxME6Xoz9HFYngr9Sh8oSletIAdRL9m0fsx+5AQdFx2LDtaJlfAze3SryF4/pYqZmvNCtfgDh4evF+XyH8IbAQ4zJDA29IsFkZf0oOVFguhGiSXdSax+1yT/tASMR8kWc6LR1YtW/pvVG+TCrigbNEOBgB8nq8OtQSSEugqLGrDixVaBY5JpjwP4mo1xw8+9Sy9Del5GGRC2YSJ8sfyrMAXYNi4rdOfUyP/WS5wKmNriVt6GAg+4gI1lGiPBQ+x+VT/yA6K/hSIS6QDOUP13viOVVXc6PWQT5D1Bw2C9iiPK1yQaDEU9NbuvjwhKcHyg591KtRmoDkLR0bWtOfTKSHtBzNdgDJ3mQ5C9JHz3gSK9NyyXTw==
  template:
    metadata:
      name: delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: work-delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgA49uEg9DEVd52dndQz1ZklEONgHrnC4HOnJB8AQiu26rbJU4BamojqJO/nUAG4h9C2Tc4fEyoBpW5fR64Y5MSthAcOtYCTR27q/xxJwQO/PDBoyjM6eUrxpyRfkF2wljck3iwiU66HiXR3wwrl/JQ9dWLmo18vEHl3IlvfuNbNH05ZVUVjWOs+3U994AGRQqEDe8Cv5OpHSOqgt5I1BnTJhShFeNMX3ODZviTPBEA4FPPJ9Ao05YN1pBSeWuCGwDumA/YVNzBhhYlAW4CztECaNpuXKtEnV7nSqgZvVVx0CMV0AUSvP9Xo49aLqQ1eTGrUp49eWlQLynUQSBvJNNYbuguzj0cEqLL/6ydtXFAJW5GF/GXFCXipgSp339hfQC/0igvM4JcrBexKs4mbmw6Hf8OdeOF1Fws9zJ1f6RMsJqo/73Xodef61opUFqv/v0t+DvZOlAFDy4cMorijc1VVE9ptLzKsuRtWwlwblzFJvuLXT4mOg1VGdsagIqWtvXHKABxS0zaf+HhboXZu89Fq9Ghiyj29DgSXziLAN8wMwSxqpiHa210MMWqFP/n8SzHOup+NfkcXu1cb1b3tgd/5zf1RzHpaCnwLEy9RomI7zDKWTzMQt86H3VnVcPkUZKdSMs5cH/G6GAn0WzIxjT1P1r3G5f6gxDlsithEaxehEasnRxNf3gvf5nwrt4A2nRyEJvjkqKsqq0x/ph3mTEQt/9G6tL1NuZtRz/RROCUDykOiQshbKSXRmw5l8g==
  template:
    metadata:
      name: work-delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
spec:
  encryptedData:
    pgpassword: AgB7GAGKoCXIwLCG2NwAZn37F+tZ2BGazpfXLAuM9Hg/EZUtz0yC2V0NZ8Bk+6uXU7f/sL0XzPt9dqrG0UBYNApsyH7XKRzov9j+lq5GTEvSxkkeWepcAg8rhX2YM777wKqfvoH5wKvEpW9znt0ZQR5Jpon3X++e+trT+fHE5x7Cl+orK+LVzZAj/15K3+L76DwxmNBFBZFDVjFmIZcTX00SRVy4YJGbzqqZxCzteRPOSDSMWZCtSVSozc525MdxxhRVi+85guazy8eyBPHQqcXogK5l7/5LK2rn7m60k7wPFnCZLhQG6GzjtME964bWcjqkQ7/VTwR/j5HIKqEUYkks8NJLJMMgCd15daUDFcml62mPyvHBTc8Cq/JmJ47YewW5Z4eJ2TtSFhnBPZsMFDIquLX1d8uZREWRx6VbgYrf8ejlFODEdKPN0mAGvJGXt/exp8Hi9Ue4q1k73Uf4NdXMaFVSYFkwpl1O4sCmJPoaOstGhrj6J1yiYoMS0rCbh0qTgxy6ebeW2On54V8L4bh/+Ve2zkNnk4+Wy14FJI05Cq/oiOpNN102GTErlBT7lu/Pw4ZRRuGTW586PjHHDPagHgda1WblACCIoCaVfEpNTjCpL2RuKKDaEmE7T7AA2m8F2F4d0voTWYiYuq9BxAlBxZWarpFp/vK+Rk5NVcifXNCnA+vpVXv16CozRVzErWxkfKucWWmiiHoVka8weHbjrEM9vYrNVAuev3jBYRJThihASjNhiSCR
    tautullipassword: AgCwWrRQ/DgGUXAcNAwEbZTM1phF/0sXsNY+IrxRG1oFgoBBbAx8+VAgUWwZ8SVAdI9/rNqlGp/JpG2F9+s+LrpxFrKZk4ksP5Y9l3vXHggQ3PqbOmU4ZFFLfn2xcF5us8ZdifRJl1DDj+WdM6vyzRBAscR9S+5dwBvbC14DygHqH2Bs6144xe2YVC42wcDsJNukvSzZLOFRKlfm3pQX08U/VcTaOjYF+PODyvIMAkspPSD27atO8CBmP49jAEMRp/nqHhYkvR3DQKLfWNORK60IqZ4ouHF1SI3ZD3Euab2RskMu4iqG5XOlFpjJAhqa7aEKeifLboXQJpHsUU5dr30Kcwd3byYi2ENC/z+L4D5EFekOCE8J2aSGGKoFZYmIwTMPUg+Q6JlhzctoX8aawH28VbskFm+rGAHqyxwSbnu14TAitZELQ9h7c6X1b681vkDriXI/WSiX6ZUVpI3f1cZHm2pcsaimzSI69Ta1s4R2lh/f+IDIUpLmp8W68J+5CHdyjJ1aXWNgSB0BTXGXwLYpjftcwzkFiRrN4cMPy0drP+UUIL0ea2J+ky8i4y8Ayndeop8dCqcI++avYijvflARdls6lP1kJrJIGnUs7060oalvcCjjielIXCcYGtj3owPT4HiBhTmjmqsJ7poCn9fF3nJXg9AAVvGGbqZYc/fNDkZ4iLH1Kd0YI3d67ZgVUm3cxukd7xgwNRz9uqfWg41WBvtqtQq1yTB+Ocem3MTUjQ==
  template:
    metadata:
      name: survivor-tracker
      namespace: survivor-tracker
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgBqHm9QD3LZwhm4jV3RoGi+7KCu1vh0D/kvAUpYwadUMfzVSWr62qCD5JNhzTV5KIFra5npljsSlIUww8rsTptEpY7tpRk/4BFj5Qf7SY0AYDmfw+I7Za1/tg6qlqfafjOoh1Fk8HG0K0D+H9r0xfW0WtkvPoPoOgJyhWSKTaR7mS/ZAKDY8igDrtR0FzrcN+T1s6q8XnQcu1WuSE52pbI+bWFeESn+nSGa1pt8rfV+JlT4T8pbzJFJkZv5yodr/5gJYJs1tJ0lcwaUdLCj1VndgBaE5I4xHcOw3SgA4CMGj4wcoFvx6tm+pNPqS80A+LE9PM/Vn1HElbVQxJDx1hkbO2L9ekxuieFxQfEeWpSUaMs4qzCKsgadIbthNM/OE7JB+pjOjTTD13tOy1TR4eV52drmN6t6ykzkCU0y4YnuS496nzXGPhhjHjUNdmNUH443C22kaDyK7hmc9Ej1KKgifhv1InIFsxuGD2+DH2lFAe4l2gew45d8s4/yqczD9bOQC4reQfi8pj+WKmKiap1eJfBX/4kRYOgR3c0+PeYvNSl56VPxiiifi8qcna23BAAD92cBmdzTDblqiWtDd0IlvHELBhfa5zlU8r4AGWwl1NEBST2bv+ipbsc0REPGRbdVouavKHgUEhuZkSg8IWZTCPcuTdtAxpHUBd+z9xFtagnKM8/cLQ0lRbodTh37dHoAmkYSXZ2hSB7y1bVsRsTG6qzej7cAvSTQMq+HaLBgX95VhhAoLsyCohWJ/Z/v5Vwp6v/jKmvyyIHQ6uDYcOk3JV0BKjzyXLX+loQ4BT6N/XrfHL0QucqiARYbvnWjp6iupZKbkGOH7RSRmqSKhMEGK0RMUwHYunmZCbkquTsgsXEyt7gfUxHledTaa5JL8wDyW4sCDzsu4JzTB2BCAW4FvkUSVmPLLj84hJzF6YH43zw7Fw==
  template:
    metadata:
      name: proxmox-cloud-controller-manager
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCxFb4rjxVGowgZgctSheMhyHQicV5Otcasjx6NIOcwkwSH1PPfBOBciVOgrzntrtMAFAZ/J2MNa65a5+nlWiONLL3iIdBaNAVva7mHP31xHHfS8U7+gb3fQdVDFHREb7n7QAiJ3s9mK5tqBjIxbRSB9AVbSOD7KKivQ2JBtejDmFrtThrLPk9uoBEXDUgQpuuj9HFhMkkc/btIze1chKzDxFrp69tBkyPq37BCYRLXThp+Eoq8YLEmLLTquK3KWQqlOYPmgVmx+a4hIi2b7qFcv4pBom9vfdrTYCd+HFuyf3+1fjw9izS0iDsDD0KP4VO2qwLyJA0m3hnQ7MPbAO+1NuvFsm/0KWxaTkYYTUEGo+mYYc2oQBfTSWgLuy7R8OggJ0pdkgFSR0IF5SFG17pgRJR0nuzcD1Vo03CyJV8K1ENP8jG/8pydKE7Vk4vMfwGpmDCTlEXUZct9mdhRSU/IeVjuAHIcghlChRXV7qWFfFUPmy1JBqLoBIcxqnR199GgLv6S74sd7maNdZ33poJoplkqEGCCz8KBt9PzFsef3Y89REhqSDnUwGstDg98y/n5g8k2n+SWJqsQ/uMugbHcYz5HlVTqWqoDl3XTtOFd9BDPvDY3cScgOhwHgF0rOEPlxoXjJYSUOInuZje+Oby4d58e156JIEwSVwGw21fp1pOAvkiU53BKYGC7qZbFlSdx9Dy7kbgxvy0SZIfjv8VF+D8yR5PQ497DJxgEuc28EM+MUSQJChGuE6wLVFNcYdx8i1OzLNyID0bCj1JoK7gl0+b4BppsgGRhoZjdpx5+hcblug+0zUBntjV/L1BPaFqBjdxn+INuYfNxdjNpQeP5aK/7IgbeDDN4gT6T7vqKwPvKqHEJGcO63HUPCnS2gGnF/MaoOVr2cGckEGgYcGh+XxvFumHA99eYxQCw3SPhH70ZqVhuA6U=
  template:
    metadata:
      name: proxmox-csi
      namespace: csi-proxmox
    type: Opaque
