---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAvD6V72mRDHDFa2etSaibX3/NrsCOIgTh4V9Aa+Ncazo0nPJjmGF+wkbvcXvThUZqBpGflDz+bm6ZoZ1xLiuBy2Zci6UHzzaOPhVqC5S+N3w7vZR7OJkNJMXKeetSoWeDBgk+CxkxtCHiNMHH1zO4+TkRqwaVGyyZP4PPQZbrHFqwrg7CZzmOmRI2C9I+Rc4C/5S7mZ/Zs8thMZi3Vf3ZbD+n4/ZGqY7mITGUduYthGVO7tSblK+4ITuoFSwKSJGvXGznLCcL1LNMDbLzxYjw7F1r/cfW6xo+kqIbCCB6NdM7kcs1b9XyiQPNVyEcogM6TwGj4K0u1KqfWS0Lyy2Ec7TTv0RbFwfbcox3RW2UEShzWLlMSkXj+bfS1KKd3BV2SMtGxWi48hhpe02WltHeJ5WJz+EkEnDeh4EZjkyx1PjWu9KtQvSK0zheV1cUGl21Xg1sOcfsdDAZhz2f/sVO1JjltAsYgfPm7gtX6U9T3GDewJ2KarzaWilAqdxs65hLr0rOQj6indYZzVl4/6LZhB9JgSHwKTbOW1+tV+EJ5zUTUIyp5I8Rl4zyAcRobh5lnTqcqYgIwdQVEgwTYTxO5WHw0ecegdf/7xDRjNqIU8MicXtv0xhbRaoHgfc9GV5fiCSGCjL/xbob6XCAfXLdgZNm0pMK0l2xGuJUHA2OWM0gktP2gKDA8RGOurbdZI1+eJm8z82XjEQ==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBuzk/6nCJrkQFG66M/6yh1VTSXSL0dAPGm7GuqyU96Q89LIylpZoru7x1+6WLCWcez4RNi+JW0u4lQwNUOqGqLECQDwuy5T5KW8ObPOFt/kucLWelmckiYhjQx99iYcXCEQn4K3UBWJ02+DIU/t8kSiS0tF6eB9EQrVFXHJscuAC/rYC46WMU5tBFkGaehUvy+Brw+h3h60MSewiFjk2ZRtnD7uKiODLVuw1/L3iC3cTtnF/RE3864BjW1gQpk3QTvMIOOm+J33SvbnlbkHMDkPsJgc6Z+j7PucTStbQ33H1HY4MMP1xrKC1fLfbxpWQiwrRyHEJfwX9bA5K5zGCcRXsEc4hR4iF72wTqEvcXHs9Gb/WLnCWy3xmr0Rb7d/Ib8Ji+2hCIbMtKplolYZEuPird6bohrtAqCsZkNVq1KKSgTJUitWZ7gGhPzAZV0ds0p1QiNHRLeAOC1ChsIfjEHtqeQoprSsLYilYGrADgpxfV8iea81t9rNrO7JZrJ1UzHon8FcI79D4i7OyyXkcg65GMm9cBsQP/Wd6KOealdYhoc78KiWlIjfesQsqgYqR7Fui++z/jyYU0tIMSMDKoihfxHpvXVqYTWipOvGzVlA/0NL/NwKd97EXb4RxakfNq25oEymKrFAm2Yg8f5BaHnSIuS7RYLs/poWF8ADyAcfeG8vdUZH3YOq/o0RjiCmpnIkUKd0/EPwhE=
    AWS_ENDPOINTS: AgDOPrjxsPU9W78tLUfH/WwOf/Z5GjhAqTMFSu0jC+tW6tlpd11h16jgPYxpzKoAcixV8Gg1ojsR44dV1i6Oxdf1k9rcYtUkRNx+vXvcvW6Qy6QN7GSr0BEhwgy4xi6xA1ToKLZxCDrEpboZ35cDvVl08rEdP1UEmj61AiCn1SwfgTnSEo/Fvii/471jFIGby1EK3z4IxFCy/MNtyeSeMimHamvwRAIN1SLHkmDzhTFZjTGWLybzrFE2SrLD5QXAw+FxtQ5BGlFY+/Jv7LpfwYpGnvn18GFt2CLC4+pfthd1prCFfuAIxvGdA2nKiTQ8EdVcXrrZCg8OzZM6GkVAZRalq9zQ/77D3ynZaQxNYnF7PQodWkxrGpU9kaovv2Cnh/V5OZ+k0GlClWzeQHbDl9coe83SzEifr7kxhUkdSCgyafZc4SIBYYgyNK6jZQ81Hfb61kqtm9OC/C1V9bg4Bp1S4sJ72qOek7PGqnu47Td8gQj+0dZxbhWyhNENb5m74EsAmDanasc1w9OhsfnCXv0OMF9G7VLoHfLxlVJIWWXAimDKqrqXKTjN8VjyQ7NeNZvIDXjDlDQN+cqyFqBchiHajRzsSgY6WQwVbkbFMkr6pemb3Tmb6AOEbq4l6LvwweigRSE2YHszb+ylO0c8p6gWbqBMxPHqljbItOTH1lGSH5EmY/Ym4GUfIhBUK7YBwb6IvyDsLuGkjtk176CN0rYB3EE9EQOjFfNrCw==
    AWS_SECRET_ACCESS_KEY: AgB6fjSf79so1inCERRriClVXrNGHRbQYqvhxWG4yl1LWi882XxaUYMGTS2ITWSgIceMa1tBodimP/tY+2HIccSa8bqVy9rUXuXW9Y9ulSuOrbpAIkz8MvGAmL8zOV+XgFvMMWJ8AU9Tqn5EMDPyGe6ma8Lil+/BbZYOh/6nvS8DJ4RbdmhSWHJ3y8bAgay5727ruE+pZbwkwigCTSEcqwMyvm2zVSyxyGSFhf3Gx7Ql4tdMtQZbH6QbPG4H5vOKUYymw6XjphJUkRMjXy2qK/iNXlRAgUQWYY6mF5oP31mUvLM3xRdJ6RfcmMkWKTJpJGxWZ4c6JinUle5Y6Fu7nGvMMmlRyenaPY3Z4SatqyK2ckYbAEq8ROzodIehtHCuGisPjb+McdkwaY+aewK+dJIOP02uX82J88ASHoETNaEnj14OycP5415656FUiftYCEOij6hx8lslSZUoU9+4yrSNRhFYFMKS01jXSF0WpZ6t0HqI3E9+ftvwaebxFk/AzRqdPhopYOHFbgTFS1J3nn/6bIMk9FJDKX2U64cPcSAlmqm9T7rzNjHjyCb9Zb0pY09lOwvnK/rLTAGmtUXgDDuAFwm84/eRy7dzXaNl+XmWD70F8v4vDJrGZOSrk74hXqheo5ss2OqtfO+k1xfdPI+mbmpCACieSCtv8/u9Evj1gStKYUAidX3u5GPY2CUS5ok7KGItCCeAg4lUiL20TMJqmHF266WPfpiLKUXDNfzeyg5bQhVsekMr
  template:
    metadata:
      name: minio
      namespace: longhorn-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCrPXfeR8LS1i/h1whBo9MVm+zYIz6TTyir80g3aHWsAdahBNsxoWITT61NgQKZLitDRFmiKAzURFu+LlbO+ApKF/JrouN8vEyjAq8ksJa+CIZ9nNKZvjHzlCjLajFe2f9J8zlf5ScIqCCG6JthgAZBi5SaK0lknvSI6AAseeDubsEPq295uZLxzDkbqry3lE61uBqyEA/CBZjLAjyPOdvKHnUtrwx/QPlQHaXqeb7xWVQyxVe1110y2O4yNJ3OjDAiyLL2NAuoO5S6exD4tY0H5Qo7bOsErMJv1EM2m7v568IFoyCI3Ul/RUJlt/iBDy0uysBYoC4ryrxtQ14NGOg3TFuC8Qa3TrL1ByeMJO4UENHv8ixG9uKt0Q/92ta9kHsVh5EOFAgsnQMtymHmBIzFBAiH922HAI1gvtpmFh7PfeHcAs+e9x2Csgku4vENiih+0lXY9Q3xQuH9bSeW2/zzX6gZh888e3/2XLD/qeyAO75+nA2r785btNEJPDJiSdAltT73Hamy715u1L7z9d7EHjxOmpTeL0E8G316Cmmbn+xDc2C6PWANKwsQJ5xCgozPw03N8GiLRRHVYl/RvTYu9MKYfMF7rZ/oMLbfAg86+9PxkiA7Qk7anI3kKFTCDupJcFRXbZdQyR1jxL/kN0pOYrvHcet1Ag2hCp6Dk/bK2LAkbSccJFBDz78dp/fV3J6wujLevhQ97WJdhXd69Z5htQ==
    client_secret: AgBdzr2E9CZRsdVeBHJCTc/FmFDdFHRfWDE2yxAxvu1uk/4HvjOlWOsou0mhUO8Ky2wf0tAtz8fv4gCGxmKgQlh2bCHHjwqkcXae3AqLLCJRJZp4JCsMbxWxWfIEQDKP/BlljG0HtWP9mIZZeffTH+42PRf9wRRrnTO3iNCk6FFeWfa8r2lb77zBJOYt+CozwHtR8KwSm6XtKduD+7tiycVZedSY4ziljuZcNnbcTeSSdHBCJpeQEydn+6mYrS6gKfEvpwPePzojO3UpWUTkXjY3nla4O5Somv9acGcq32X6TFsrXbRpo0jjD8e1OO3VOgBstX7wihDPgjkDhFIRSDs4bJWtK5YstO0nlK6uAVQzadvSsXBhdaTBA24JAnFLG0KG1ldGz8kp5QNfIwEFEesWSGzrGFuHL7Ni4t4Blv7XfrPNVn0GdoI8MyLED+9VC+p9eQappRxDQx/IxpdEP2GDATxfyGrMnqsS9865g52W8W5+vlDUc72Au38Bbb/2R+7IgVArBNd2IaVa+F1NpeKMmZnJJblkGcIzF+LZR9nywJo9vYNazAVpl7l3fE+urQarEwSfBZ5wO9bmQLuF7Soaf1FZ4xH6wGaf93Cjm4nSZf9E1ubADvappFaTAJDgfq6dIOhjVaaNX7BL03zAusafnBAGQMBgC/DCLi6wKCoFQdMoW0HRxaO8esqmhrymzbTNhpgjkCMuJeD08vPqsnnbQEkPAuZ9jmSjYy2FjeAXqG77/DXnDiz62/LiZLXupBIkcKvTi8agg0XyHKELgE4=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgAW6CVjZ9x56tSxoVQJ0nXW21vSpv2lk61HqNUj75i6si4HbNuSLxiKsod/A5UI09YaTe7IAz9cdp+V71I8dqysEd+FsBWwBH5Ivh8QrGT6xB8ndEnDaJ5VStpNpDQlo6Gzn8nMbMRpTW4s174PIWSesP6AxO2/+uSmDbUgHgY3g4qWNE5sq5XHRyP60aA/9Kaoyz3A4+itm04vU6ryvxSwbU41/0hKXNAo3h51hvh644hZILcfFwrmrU897oY7SkJ2Sue0g5s4yoGlkwIZZnVEz2OKXFFDNZ5yGa/wLBcSq8BUXQim9u5u3k68hRSy0VeoPjnRsl7MZWnmMGY4Vcvu4bi4z+ihh1QLz0tjqNEO7MuGJKFnPkmIyWj3IKfdZFwjPtj+icANrCOMhhaVoQU0Fj1264SFWAo4VcOqm3Xh1MvuyXmgksYlSLfa7tWMZ4W2UZRsUKmj7NZV8+eP7Urk1XuQaluJ/fr3+W4YIa4BgAMWAIGjj2rBjJZMzNKu9CrLLH0cvyLq+KrzJSThmvSOYHmAQ3zVBUxfNBUb/jvuoZbcCd2Ihu/q8Ea+4HXmO1bARQGJgdFcI1vUATaO5xa0mp4yFth1Nrb5fiWlKZ6Y2CUHXa1nOnwoWtG8y3n9JxpqvSeltvlgBvmBzob3WcJVusywwuhj0MOFUcn0CqExkRfhzewPxbnrK5AZvbneXVwkA4OA9TaE8Dc9c3s9XkrYYbLETzco0GDi1bfwXDi0NMBlmDitoPJnyk7IAg==
  template:
    metadata:
      name: delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: work-delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgBZH8cnM+2DExjxekcJr5TaDXa6ft4isldFB+SiwyrUys+jQg2VgPjMFtOnzbH/Hx/zVEnnVv5VD3fYf9WE6Zq+3fgK5IfqaQHuxu1c9iHoUmpu2yEd8gPPD1m09bOU9GhCbUjNn39OJyaF3SJAJL8tOmGVCL2pPMWhL2ZX5WPIbknABmRExA5RI4hkh8Zg92OyFusBNarlFQL3lwLUtRjV74R55odhKa7zPOl2WZs/y7xT0o73d7/vvxrJdOqlclHCUI6/Z0zo5YhxioTONNvImPM3LvaFXjX2+dWIvxwJ4OY5FpuJbwQmhX10i13pDUW4DfbyG/mc6VivuxKjHOAjt+URhp1DHWChrXCYBRYassR6sOClH/jdDdx24Am7qbKm2ofP9mgwd+/Z0F9qCJJo3nnfGglJxM2HJosopXalVzmeljxbn4BqgwQQJ4w5/0DFgudKbzd6SNVxEPdDp6UDj3XY8wrBn5kbSUTDrYzAxfV+ovHe051AREEYsbg/hidZpi5GHDlAX0EDfekLThvgktZID2Gyd88jG+7n0qcDcR4EEqEHeipDT1gG2azJOpYh6cnYezvCi70INJMKrDQCo06IUktMK+hgJTQKblJYzKNNbl5Olufts+2VswTc9aI8ErwR15x1QmCiRqwg7BSFOw9KHzaWcr4HM7ga6+WHLsZfzBS70twf7Hn/PyrmSipyRaUrujiFlBjAIt673b1PRUC2O3PGL4kyx2JVQnOzF1jatrJESheW/GUOvw==
  template:
    metadata:
      name: work-delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
spec:
  encryptedData:
    pgpassword: AgCz5Elo9jAwXshEaJH8OOJVqKxGpi4nFwK3/5tLJco8YvdMGSZSSghQJvia24Ry9gKT51nEcrit+wsFhHCj6G+d1732zKb/R7cV/9v3bgzFheWRjLOUiQCZ7btA/IhoXjWxIuU2jMsKYGNV/yFAg2zMw///GEXS7db58TmyHqdlUM6WgrGoHNreaCIh3X7IGtr8duyhUMo5QJdl9pvNzJMAWP8e7uWeH7WdI0gt9PrgIp4mPJA2R2HR4fIAK8BZOmKARJEP2zdBcR5Mp6lUSpFfiUrx8RDg70Gs6AENzS1G2/g7HvqHzubcspkLAqcXmDhR98Uzr2DwBt5D/d5bKGT/qoyxgRUQA0z2a2wiW1opnu30sPsf72EewXOqoG6pbqB1oSoat6V3iWbLbzXwhutQ/cH8Xzs9DXzJmyBOqo4s3I5D3bShCc9M0Pzg55Z8H672t86lpWz5xHpog900a+/IOJFz5ZWPEoGXlyg3vTPUavaPCm48UNU8KAPlTpHh8Apk6QB7QDi1dY1hChDXEb0VDf5H3YBZ4hs8Q3BM+kxaOsHM03pyZbZz5m/9qlBAkgeHEfwLfRgSpmnnSIdm0qNEkyvP7FzIx12tPgNCG6U/AXJk31UQ7XnSi39zSbQCv0Sus/HyYGFXvdCORw/z6zK52Qv1MOQ3LCK3y673oQ5tG9VpuWwjqfBAGUvHtKzOrPJgohSAs2uqiNNwQFKBMUINpEfqcSTuqGpliMH0GYomHzYtznFT/PRs
    tautullipassword: AgApoHrcyb1/35A4cpOutMlE5Ub10vSSsarKtIJM+1FT/EBIOg0p9hq6r05YL3Bn+PcM5lLqbKFIRXgox0F9V4Yr0WRg+FCPP/dwHKamuDnP+HlUFbmiS46xgy1HZKjb+Ji1zqdGjRxckLTzVZsL6nMJQwVm40UpAWVnyo+j0epJIOdvlamJ/6SvYtmZ15HzcB4TveS3C6sSZ3nJXdDHOcXyNj6ky/tcACrBnM3yHrcmgKNYRhM+ZeiiiLsHbsXxyPde5QIMnIaphDYmkadggmyb6EWXR/XhSBGKk4+BuFzl7nQrPFtlGkkE6Wd64KJiVN884Vuarx/OBgnnjqRctY8IXc+7h4GFo5T6jO5+LDbIKLWIRitL8NIj94IixeoVCWxDjL5AMfF1J1GLUv0pk33Et0EQtnSzYh8q9GXgWSa0TEW9loCdk0M2CJgCzVSMAamVnsOjFHekQGC+JPxc8ymloAsWj4pfV8EzuE+F9FfUVf1YS817T31EE8L8HyhxVGqea9GEsAYK9KynjvoVxrLzJFo6apd6GAQam+oCoD9/Hsh+VFp5zg2ayzjtuzJ/AxVPbAFxApqS/96w2nqlCCsrNUM+u77T2YmDpTyoLouBjpbb2iC8fLRkxwzih8gDTkzMsnSjtoyla5LhDQ8fywoCon0LMLmMXJfVp+w1ZB/P09nz+qIA4/GNlW77hSdvUWGTMSzo0l5hINeo/UYUlsiMzFyB/TUGuZt7Fr+0ecNq0g==
  template:
    metadata:
      name: survivor-tracker
      namespace: survivor-tracker
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgDNSFIVbXyg6hLgqSzPi9rCCrMmPS9VLhAsDkdGBGbh1d4CzcGuKdhsQHktBK0M8pQH4uunkFr2XswN1HWS6SC23Zw5wqrODFqNXRtaeqfFTUEhlEWcl3JDFZewxuwgP4RXuEsSHdDZ7W7aB7gTfhaFNTQjwUsBm340TP1uQ+JKtsHbBVSAO26HwGiiHIyCqYJh5PmYIaRiK59XZmYP2GddGphA7M3Ex5tavHB4JKFm7Te9BTo0VWh8tRrWHxf8guVZFrQyGCbTmKYF3cmvV/mDWJkudJGREuZLSmm9x0UA+6Jah0esYKbYgK1uFMVvUo8xpy8//zcoDMx1LWe9LuJ8Tvy/XfseA4ZekN5ZqU6FgijimKGupAfd/80siLN+GR4RMDU9u2d+0rp9CxvOjhNAOPyUvKc3imzIzMbRUFwkzThsaJ1i2edBtWVTQdDAeRsA3o1jE9YtF69BSJ1zPUJ3Ha56iaNPycJkF0Mldl1Y7GD3pUxWOFQpFdSczaVbo+LfStPPYKEa0F1wVr9R2GTxH+hA42v5JmMZqj1N0hzAlj2huvEGUeVHXQkmb/1vtjhOkVzPjAtQdbGtbfYDJSdD4hdOIuDB0CXTTBCFAR3fU9V7wHI6OFKE0Wj/6W2vYSsTTDHrOCTo87hfK5C5omzyUDOrHqZ7kDXeo4o1MdGp00u0xWMpwI2LrbxxHlJy54f06bQ+10B5CB0c9oDl3NWciGVr6dBCkrfFSGsmMJ+xs8tjdkbKIGSxW7OrHo5NPEqCxtHO6+cq8QRSSgKTePokC76G066SPiq3xW56cP1fnZKIdbkW7TNqd39G3SzMtEF+D6dC2aqIZEbILXN/VqF9WwhKzCjC2p7MRYpzAi1hqeMDITXF+dVo7XpeI8BdrSLwmDWlPBYnZoH1wRkgIxi79G8XstdbYbKnU8es6s6mBdvwxw==
  template:
    metadata:
      name: proxmox-cloud-controller-manager
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCA/+ZrUQi/3d8liU4DpxgKl3xelU1XtTpo+e26HDrGmRCwLDduW0l3shrzpMHziP83v8rXe48hjvdJlhdyN7F/Hlu87bRDesj/2P0I60Tf5r1dNTeLqNksrFQcIK+hp+gc+GT0oZ2w2BCGZwak1mWljmtHucn3gbnW1D4FUxaJytfmUeSy9tx6LyiTAMZLG09eaNGsdVD2M+xREiva4jQNLzqIlOQGVC3eDzSZYR5OJk5/57rTwetUyYxT1kQi8mdHJxe5pj7mtOaUfQTYyDhL5AJPFEdaOV2oCbwptgzjrtgZKfEVUbuwkKZJHDpdJBA+wy2kjA2PTiZpBn2WXvcrceBs5YR3UDQQhXPoxFmR+Wf7BMC4BgZJjsJCIeCZvTdW10FSPGto3qhJp48Crz+XovJwHZt+wz/dNX5rgZWZXQshOQKCoxXNPp/Qtf+YqWMifj0ZwicdNci5SAuHIG0H6HTVNiKrsHb5jYWYQ2oNw7xeMMSe/BBbwLnMC7n+xbIEe+zSDji5B5jyPqPiDwLRQ9C2ymjn0kaSuqOlm5YlzE4HaY9E8E0nm+mQ7/QhtzdzdIb1QOal3k2P5pUP3UQGaz5HUEtI/jeDHkPehH3azcWheRYzSuHxHPAYpEoynHdiuk8xaV9wetlAEbk8g2opmQG9AQD3TNMkQ5msr2WroyB7L4uCf7fv6GqPzZlnTZVoHBY9k1IOtPHOQx8BwRcKxSvU7nRR1rs80MVsS1waeTPiz4XlqJJZwHHh/72NPi6xUolZs1lRTXfPNv5O5QggtOgf6AUmp/902cxNejAFlwsV6HYcZq7kAw5tB2u60Ze1ZyNS3L7ghdhm/sOG9cfqFLkdyXMLNADzmxSNWACo4c7oUdqwxATimyS/or71CVheG/7GlSLctYwputS1MQGnbd4p3E9J1Mi6h8KoWHYxfDAXFNdFC3c=
  template:
    metadata:
      name: proxmox-csi
      namespace: csi-proxmox
    type: Opaque
