---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCep+v98vvFcP7YEGCpDrBXXFAvUwubbLeZ0XwsH+TOOK0rg+/k1nnpZPu5uGH9XND5N5MZpiSkvAjqsxk+roFWFUmWMBNWzA/yMbxuRHN2KR+luGe6fMLER6f2jup8TlktREB5Ud56TMs8LbjQ+rMd30NACpIffWtqDIeRYpyiLEkNxksIzHkot80yI8J8Y0wYfh1nU30dpP316FXLqOXo2VLCBI0TyCOov9oNKFsPT+cGnyKtf0f4TZLOSHtAUs4uxbg902gUVhe0n5+nDpTjUT/FQWY0t2pR4piyh38A84nm+b3pf/sjjp3uiQN7N43fPSl8yI61AJvkf9u8TzWT0utFkZijC5IzeVF6gQgu91gj9oxwBaVqpKsq0xvOd42mTKtnG83d/QlBUX2kP1nUSg4xAutKWncHN48OPY0Xulz0f3yTEf4qUQbUME03PgxO90/Qz+okGq6gD48fnmLIRF3siWdCYTOsHSt2cdphYTuViSUJqpZq1RK9/0mmqrgl7YOMOBIKj1PG9rGQV284lIdqzv0cq7vAXenBPgza1lT82bRvKSDksHtCsJJtK+Kho2sfpmWF+cCBHo/qc1QgkV8Oe+gJVl0hk/qrLFxqyeMboChpoEd4XjGazJCsprhhpESodw3rxEmb1kH0pHDW3ekCOcC+RwySpJRmmFM0zNlJEVZiEgGt/f250nxKTdt1yY5qQB5d5w==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA6V7CF0tzry0QtBrlx84t+WdGvXe/+xGizXozbzCC7/jH3adEvV77CHbXRdoMw0+HTfzg815TmdBmFEb5FVxwth/bQWybWX9WcqdPI0SveIoXpFu7sJZzaUDJmCEiXsClNsF6hxxLLdyM+yNgU2Ztw3MuTNHQjWzGX8x1qetZKYLh5O7Nk8Zjfk4Jii2qBVbdpfPpMRA/wbE737fLzJKth7zOMSTZLDkRQgiBbZi1NJrqeiSgZVlQp0kF2//rUrJvQXxnNeOaHy1ubFn+RMf61FhIIBf4PrOnmvfUr31ywvdqlLGfqrcxTGwAN4mU5rhQCcaJcvSzriqM5Kzr1B7yj1fh8PhZEQHlsdYxqC33xCxUB7UGA8OPo3ns4TTBeJCkanVnvGjYVvqFy1dhGpURnljJESAwqqovdLN8M54j4+f1QcuX7X3xXWmxVbNjW1ZTRHEB4CGeKeMqAz+AMycxNuWZpvZIJs3CCqyIRYTig1gHrPxfWSyLklYCe//n1CAch91jj40F5BoH5Y9kw6DtqfL74wVMcY+HwWeSzcPMlGIVO5KpivnP0EdpxWoIYXO1zh6A5fSpAVsiZYUCoqUfA8V4ima4YkdrCH2/1bZfoA5jhrhZ43ASb4fafMp+dRvkh4nTCDlJBxVgxFf3QIqMUOdBt79luiXzBRHMWH3QtNnIMElTtFXdcD0qceoMDDoP7KFrZMFdxWqc=
    AWS_ENDPOINTS: AgB8dQn65X70BqXNXzWX4/QZh4M0D3OsTmbmU/NzrJuiEKr+5qLS5GAt9dMdEBdXGTjEppIw0Vq112o4jfsPhYU0bDUrIBAzXeI6Qz9D/2Wht5RFKxbzbhpSjJteGqltuw4YYf1ejSL8I1nQ+EYWqt+oc2nwnfs1lZ4yqBtj7KmEKH/afWFHFTg1ijO/Fb1uW0s8rw0a2YT4pgFgOX0UOGVe4isAiyQ7o+LXQa8VyLyEw3QflujEbe6cRQOrCNRkrGUzdhMMaEWPkUbXnYkbSTVob/0Wpbax2KCM42EznV3LCEIpgOMDZn/ET4WZSO6DM53deOzpgewLRhQzlGPQexOzMQmkNQAA4rNdTU2XTQiNgTkWl5T7inZk31pdcZzaBSiRZTog0vrvrk45GlsGDQyA8M4q2dIbg8WS5aTKUjKWWL1l4uXsCM7k7BmKX1gabq95brzPLxYzwkrgyjntRhNYWgmqnyLbd2ihOUBePVcODTXc6XvnFkUlWrQ8ir9vBKckj1yXv9YqplJUwEDcpXlAteGW4pDzVK3fP7zu+w6DFkX+8eKiX8lJYZ1Mgui5/LsSqglNyfwsqXZbnt5nKxEMVMG6OBuecc02H7heaBDzSA+ZKuvWy+9aP0+Vd0/tTMXGyS/LT8KY2T4NioiluqiUdPKECGvylB79QqHFbvXhIaI+abbiXeyCyC4TASm9YuQVULXJ3oCg3q7fmIimrw20Zc2gRxd7WxrYCw==
    AWS_SECRET_ACCESS_KEY: AgCXiC7W/ZUrtYeQD7jX6pLVhLSfwPdQJi2ZdycaOra8dc5Bfhvyi7BTQ61boEbNxNJVIyiNFDY+Zlco9XF5PK3R3PvGeFN9VQC7B0WmWoaEdSipg+h77L6XUk/BkQ3c1J9g7rJPt/R+ff4dvy62OOvmx2kwtw3EA+aOcK/God19DmjIFzkMh7uRe5dZNTy8bIX+nH4ywTPulBZW4sBp9Faw0w78gewM7rv0gkwBfaW20q5M66As6l95WmMjLVw1xfxnXfdbZiyGPjYO/xDXAGxnQSsIL+FNOmClvmjjW331NO3w+XX8UuxwDH3b9Fs44TdZ97rQeDlI0Xsxj5XQkW3DC7/Vr0oUYP+Y98AzC9CViZC+oBAk4JVaqIurheUryj/PlTZ/3af78xkeOFv2H/bfqJEU45hIzz6MMuvNaygOXcRyOTN4FOvlEuVq/1zPvAZ3YkI3gqaZZiYLNAbh1QJaD3Mfkf5IZP8HcsxIrY7sq13dhILS7YSl5Fyjkd+oOdbBGWUd+EJbeZVVHR82vbQgnRYO0jhXxqfXJYCEbmsadchJF51Bm3X/x9z8hltDIQp2j/PPIm9448H0j3k5NIujAMU4li1TaH8HJPkgs/PpZHhvkNbHWKF5u5/HHpCEbQFRS6J5HeKy0kABj786Hd02qKDvkzv6xOGPCy1rSdzZRsep9ldAdnQfZls+O6cz57dYgC3ycqR3T0mKI/i6TjLqaK3jH7e4ZM+/oommEX+mQrqBor6mcg9/
  template:
    metadata:
      name: minio
      namespace: longhorn-system
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBkhPHzdZgpPfuxn01poGlZ1aVrP/wDpu9wrpKmwM+EC8y7OSCZgG2IkAGhYCMRDRPKXAN2Xr6ZgUgriT0j5sYFiIgI/dr6dEA/XKFU99bRGxWYXEAkS7CBgXH1IKsis8Y0qfJPjoulyn7QYBYPzL55lqLEROwOv67Rdai9nYJA1n+wLH40TDaKW24wKIT4uC9feCHok/MzGRB0qYDQeLruMFYDbwOVmtRYGI34nPaRoig5srH2P0tLSHcaKzXCkLZLcz2J3NH7LXUjPN7FeI2mtMrAXcwClwrd9ebC3m500jEem0sJrk34yawfCQqoI3Nmyok5m+qWyRpXvTiT6bjN+ftII/YxXNon2xkGWYs3weqxb+6st8+Y93u2K5czudOF+n1YewAghHd2GKktkXcaINJttmEUpXPIhmi74A0zkSrLEpxENMkokOSdR1zAfVywRmTw9pQHWbvpmZJi0PZKOvBkYBmgiqnA30flS1Hjfhn/FOOYAD0LxzDnGLE3EyaJMhWqgZ/mJlnY4Ci8p+Lx1uu4Dc8eISLyAJy76gwqW6+r0zCnz4PVYcMVwlbdrEPQLvRZUjxb3+XLjETlENeasTUq8RX1AM7Tc8i5Zqw3Mi0Dpo2m/WUSH6ha8bdftR1xapY6s7sR+lPhHMsLAJU7BsWZvPefa2wC7JKQSgCWA1sbkrKyL+9tmwJFk0B2F8bg/javJtQU4AGL4xKvMSkQRw==
    client_secret: AgAWkA6oYXN7TE65KUUoezcEGxMLdEdPEJpJrgRxWEACedEtczSp2bLFR/CO4tQ2P/Hdm484ckseoAgrII94oUVoKB7pQ2Hm+Oy1kDZGbG8VcGF2M6IKIiixo/qMPvfOaSL99ctIJ0Jjc1o3yI/UzmyhJF58QovJouZrSjS3S36a/ASth72BDDXhKG9mQBq0E3WYeY9jxb7HaodVNAegY7nTymFdPDbR4zO2A7bYhfHT9LqzUYIgQLREUP2YxTidwDlvW0edk8LTBI3Fo56vje7QLTBGA825ohDN7yQR0I6pwMRWnzr+0Sn8xOCCtdo+NmgutQTPWP1d05KUeoShJ1o0GnE+MLl+BDIzWgRozb+VjQSVmX36AjdFRYJe/smB//JgCneGYp4me/NH4LluO/rnkwm5rf/IamobpUIRkCHxmLOTcRknnMq+aDQoNv1J1J7oWBWiQcPULghyno7DAja3mLMmMs6ZHdkmCYb9qXy1DaNittI312LRSePWn2xdBExgd3sKtLDnbWThLbHKYfYLO43UDAUNBjuMKO8UTuuCfT64+yUE/58NvupCxiBw68nOPZpv0V3DGKVUKEyN8BUnR9h8Z8kHeK5Mjare1GVxXZhu6Ut2Er9YRqBIrdtSEvhwmJdQm/vees8OOIKHOhm/xRO9aR53AYyG6Tu2smAJI9eJoePFb1rv4GEc8Q+Gktpn8C355NNTL6Xuu6o4inuC43kb0QXQD1BU1ZEJMipavk4/OSQtrF0BD0rFDvB9Pf22S/NXqnQ263u4dX60fWM=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgCbamG9i36dUcArrcJw+8K+dlI4x5IOuY7hur6H/GhyUE45zWkfBRNQij5qlTZutNZD9nQMocdYqjmqIFvorZY1OljfYqDYDBmOliOH8bVjtT/IQLwUO4RFYfb8m9Ae9qYNJrXwz7OzAw+EsFa9qvQjD38CJH/ElrVsWnkL9FNtwghB0Hg9RImJ918qqXlLVjXSJhx+Ix/RntrSTAZvv5CGSHlvzbAfzsoHc2W0sV+f401pzYK7B1C4Jw+2qMGDLuclUL4W22E8Y6Ej6FZu8CGBKCW03elYHStC1x3Km2llV4MsVhItiy+4gjwBdJsRDJrD45vXKN37qo5yCsMuU0ejd2l8Su7wr1lyZZQtM5jQYZJdBPNrM33Q6gDXrs2tYoslcwTfc1JzEjKNvmxAk6OYqUzisdghWLjMty3h6GBSKZ/YOxCHGXv8iO21JibS5zoyOnMv60tmgOHP6gIybOKtfK+42KgcYXk2pV8lKKkxqChTxf/gTbLnwc4PSwofkXroKEytyBTEKnskruIoT69mNuV1xALWHcjgSYgAt44wJP6ofZVxm63KE9zccwiWBNHassJc8WmYZAlobCQGZtdGb8nDc681tPTHS132n3ypXYzbbK8vzEbEU6yCuMklycnWlRTROOdBi8q9kSEAyDejOvmHbtax6Ul1lz3Vrml522o60L9o+sEoI2tB9piupv4KTESmWVrw4YPCt4WTQvheRnRYpixb+zJCUwfeq5vKL/RaboKlDBGU6h66qA==
  template:
    metadata:
      name: delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
spec:
  encryptedData:
    pgpassword: AgB+xnNx4AE9gnQFekGrRJ0cbCdYAwJzAMRHL+7QmmdOEPbp7gkixvslp2ICde/xmj9GE9Im9TKgTf1StyFBK1x4iqbR1jhTAY1sFQH5RImDH2IiJFNsqz9L25QxlNF73IMOO5L1M+HYR9FmggbcU8OEhWI6b8afxUB/GUVeuTJKqwF4HRxVG2Fgj5MhVl1401+2nYLibum2y4E98wnkUT4cfUt8ghuGvt/bUWgtbclKohuqA8snrAzSmnQJD6BMeu2YWUCmkKeL+Yi1OppW4HhovAmcf30qLjudZBaV+Uh+ncqVOlrm6fNsfGt4F6EdbEb/Mq/yiCi5d1/d2NM8rw9yXEGI0IVVfNYfvj9/ORHPlfyJGMKqCVUoJwTd4PwiqxKKlm5fiVWjmqeaQAIg4Cy+r8kEhKe/j0YjG8nfzwK7ooxlPqTiOzIQRjEfFAjd57YLZDGGLUYIZdPGmXNgq2cVKHjt6pfSA5Dnin6z0E4BeeoMAyFj+WH0Bl/ondT+B/hckTJz3yKEVzQRwmylsW5obtVpHUNFheMXLIYciOXXkg461CMQOeCMb0+Fyou3/Gdc4Rue11pE9llvPU99v6ObrTaUIoD04fBWCPyBamBPm2eHaO7oV6u9OsLLwMjmnh0NfQ6Zo8Y0Oryw5pT/p/H8aV+NJbSMhtRf9/8Ta4G+CuVmwAKGMxPm/928Gj9zZdeEi7ekWz6xfwZWUvM6ZeNAwmLJIMdkc8tYD5s/1WYtFxNOsCR0QQsDCuzD9llhBcMuPjUYfhDa+rh9GqYLCGAtuakEZU0KZA0CiNjQGHVyEJR6XxvQEgqB57ddX/Nup7XuZp2XJzk/jWRvWLRUcEosoaOFEd9IoTgVG7x/D4BnK66QfTHjw1tsRNXHdtp5l11Q0G2rN43lc3yDDuSFaI4nXaF4kKno8HaVxd28ax9RoPsD09JVWKMYdXeDZoO7SacnGBssxDJ22yw=
    tautullipassword: AgAL7PIjIG3OirdbVo8dxK3+/DxqNUZYbJQ+cJ5ycTv6QmFNBeYeg0JKzRqG4vSk1RA0DlEDxasHzTwoZ0XQFr52XPtIfxWGxfipPrN7gYIkNxrKtvNn2Qx25ZlSpFUX55pKSaxAC7RXIwSsKt1UnaUFeI7rLV1jZJEd5w+98PQK6IBc4SH+DbddPglTjccFl478HwJFGIBI7Lsnt19lpZGbgpmvyiKCUiDqsTWmWxwqAdVQaKSLFZ5ZRB2u7pkXnCjP1uE8/RYv+Ma6SDI474s0v5g5m5jMbFYG4BNsSw4ZyTeXhF4OwH/8LdLCgcN4yyWD0PHSE/6JJu96mOK8QFsba5XkRisaEt8dxGBPWJUnCWVo3GCPZuo/4Gj+b+MUgkklSRi3dbJt2DKvQCy39NmIDoz8H73GlxezeTE0a6d4yV09t6RwRt6SiwvgkuwASFqvqUJvcXv4a48owpSXM1qFQQUS5oNQaa8Tv6/PUEwo1PwVayWQ5wRTpgyfgVfUgXln0f0S4JIqA/+6ofcQmVNQzjUGv6zCCCTwIivxNfbe1AyAQLH/3IGc+nDLKXHTUYWmcamEoYuZGEuAOmQff3KAXy/ndFmwpL6K8lf7tiUlnz6JGiyh4ktsKJO/7+cI6bELVil7/vXRxHr04u3RH7JD4UKP3Nkv0+KDKVtEGJNERMaaqJ8Ny74nsTxmjhCIZNmj9gSauDyeAAEJOTlTUVS/XVoLQB49KvR58y9WD6LreA==
  template:
    metadata:
      name: survivor-tracker
      namespace: survivor-tracker
    type: Opaque
