---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCHg0YCKfDa/JAmHBblcwGybwxWzKpBEiRre/UPrJRR8ppViUUd9kVa4OY30GIgnNMMC9fT8t71Rdiyz0B9Zf2heFj+ZzBV+X0ul+bkhWY8gkmBegsDnZXXjlG3IuC5Cwy3jawYx20PGtr33YWSengmXSft+w373eaWYGgndsHVOMsF0kaBzgI0KgxgevS5UVu5bcyghAry16je0KMMvkIW55n/OB7JnGFEZ8BoZcZiQ9A8+vAPuNzE1BPwrSI3/3pjROzzCBg9UwS7Wn87grfnrfJwyyYJpOBIVLBRjLosee/zSopkjnbY8IJauMnl6PHftHv/sNO2r7vmfF2FY3EhboAIcexsh9QSMkn3c5akG1JDP368PwM5kIJMq+FMKTnqbv/g7ZciC0z4waftbcOVAOLL1TdGLCGqOYR84eMQd6X84SyaKBKNjdrLBrLrpbTwaMiq2BH1fHOO4dLT2pQ09OlrZRwFCQu4fd0+BA5ghTv1fAWXUxadLSuaUG5DVHIXnLKJEPdhsOoLkprcZ92GR8e25GCx5h0kih2Bn6NtJ8zWjFka14hy/v8mpP7aFj8RIjfdDxxpgfdlP3UdVYNcGM1zZ5Ql/8EhInY63Ue0hfYDTrBJvrvZO8O9k8cxde0yj26QSO5r38A2xiQ2kHJo2h6s1w6ygDry0mTHIjvGerRrvNiSiW/Y3qikMl7R7UtPcMuf1r4e4w==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCyHcQJTZkxHWOrQbMMP7hAAEzbiwln34NXVWyldXS4lpDZWb4V04BgTgmn8spK8ywCJF5sFMpVN/BHe3YPi7nSg2ZrCJAmN3d+wMXj/ohxGBMRW40HqgFKUij9FWc0He2bfhqsxlV28ajs1IF/7QnWUpQG/vQpPtaAmpiOO17Y1TQUPPFUCUbt+BWUqov9QwejORVKokRpZShr8ZVIVBBr+IDdoqC0bk6FQucodAC/g1oQEzvoR3tKpGQFcK68qZn2rSUMc5YsziC6GA6YxXn8LOM0Lzw/xzd+HkVj2apRs04iWsHsH3wSRBLNjdCQmzttmSmx48SMpYwO4aTxmAKjD44LSpxub4kUm7x92KVrrazM6TNXVg1mMYd9f4XMvNq3DNs+92OOS5mao6Tl/gyjg1q8XRukwGkGe+LF62q8K1t04+5qjPyZaqjefoIdzOxxyrWycGXcwvwpDXuSevjaTGd6yOLCXCIeefTwsmBX28MBsMJZ7gB79YUuq4ynVN7XQu6ym55zhVrnux1RBSrIs9RhKnWnIk4hgmdYL5uy+4QiOXtXZerMUnmA4iohuovXk/brLM+lo4oYVVuwd6yT/NF5TeEs0VlMHyWCyoZs0jQEAyc7+JGyoPMknpOH5pTEIgWZu32eDfBeLQeb3V6I/Ao/DDS+D32Ce0hMPi3Q5Zq/KRxfZ1QeVBu0Qr6Nua2BFAkOe6ciCVBeUFzdj3TKzw==
    client_secret: AgBGmc2+FCs6AsaWV/tc9MMjn8eOdDXYHS0/dEVRokUIxuT26ftw9PjugoAywaJLLuU4+4WViHs0/Rvq9LbV5L4JAHNJU+b0VA4ILLusal7NSxQCP5jOYw9wIaRAZOvygUh1q6TU7EfMbmt1Ci1KoCOb9m9pVy1pF0Nb8XgJiQCjJDYTP1YxUXent8mlUyyIhsMsQiT4UgR4v48DWQBYxg6YLnP6kAtAIUd+CDfJmU+xudkm0/5iHXWypMnJ+aE0sGVJ03to/UsjXbuFGHHNO1lpmRYtkeNngwu079A5K0Q5mPldQLDkzNouRRThxgT7h+/4QC8JH2V5V6f98YZfpdiAwhM6eojNlSgawKNBP2kMun+BJG9grqXuo01ST+qj73wjIYuk/70yCBKw9NjHBF8nQfXbKPvypcTzVysAjQywhoHvXsbxZ44zKF325hACAddiUgFpZSS/97AOdWzDqhesE+33qDiO88iRXahtzbBvGi8M3nPC+0eTMoAYSqZJMs2JZCpDgwnvGfyyAwzPjfaE9tjO1U+qTuTI8Qrm+VyzN9A156WvzRfLcbm6YaFE6/iC6iohfiZh5VRNjDNPfGDgyNbapknieWvr0jZZS+5keknpXyvzA0T1gBvyax8JdUnzDb+78iPXsjJJMOd8aq3F+vyBCOBB2Ltoc8WmnMexxrDY4l5TKDPW6t0rY+Ef9aqQhVVcx3lZLru5K9nOS+4UAdpAIA5PA4AgYJli9fW9XGB8bEaspfY5e++fn9FlAkGPyAthkYJu87S9HTuplB4=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgANQMc6IV8uAxWikN770M1aBT6d9Q0YolZM4GWhNUPLpVLx6+2HtCNdkFjdcFsd0Ry2Sf/ZOQbyodEkznA8lyI+HmQv2lTuD1l9/T9uMM18QmpSdqKXqh6nxqVoQsrD0q7YgIxfGUlFKlMxC7aF26yAI8hBPjN7mAhDnSyac4VilOJ49RkFLzfhdQRakFAttzTo09CrIAVQgreWP+9VeR3pLd0Tb9O2jB1D6SmrHpMecbBJUJBGrjaWie1qzVgkdhWMW7x8dNonHxvpSmb+Xyxv5yAwMrVoC6s24n40XjauVS1/vVquY5rDq+Vi/6ZTcYwGfMwB42zTNo2JRePQC4Oo9HdQmJppCfY/gzOuywsU7xy7idVuNfptKBV0zclg8O+D/Ag83+zZWfMb0Y6iyTwme3lg8T4yJVovjZE2d1sOZl/C9Sd0Her60nOz/RpASknnR7SF59XWhnOb1zCHp4DJqVyrdo7nxyrQ9d9F55m6/OhNRlJoyWMvL62mnnyHtHQLORrIMpcNWlS+g45tKCL/ftLmEpX/zYoXwszqTSrpmtultdjF7D6c0FB6IkHgn8Z9lTYomem4L+LGP7GbV9IjDw/HVfHeg1akkIX78h7/Nh/WRaw4wcodsfWUSlHdmpT98BRtzsh4hGVMqGdLQQIzxf7FauTvMkbfi/phk5Aq835veCcvgEjvOXa6h5iWN8fWr0zNfVXTslkUwKIzXc9kv4m9OktPwpu3jGDCe0/FJj7Em+0+NJPX/XOtlA==
  template:
    metadata:
      name: delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: work-delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgAsY5Kx+DstPztg0ECbzXt4V1KHXCKAzrSsxys909eGkZc1mPcYfC55puEtPwgbbllLNqqMSWnU8s/sNhMoVY8vx7yH+Av1e1I2fgUcxjlqg26xxKN7D/JU7CD4U9TcCiARXEPAYuavq0y2s0QwH/36BzW73k6aQZhbDEbviqIKVsiV3oYChdDrzZmpMKG4UYz2o3pXcWc8P2jxM4DQ6gQJlXzdGCPko4FIy+SWx5GZ1/i0EshpvBRPtyn9qft1YJ6bFY5TNn4uwYkUq2yZUSGKjAKyM4KjTprQf39AcL27Gl1RmFwMxTC9oWJoIPBoZo9AGpgeXFmylqdA9RkgtSppfz0/Si80bEyiRueEnAxwA07NVSQnrLCDZZ1HHaaVsTUfSThvhUTUwm+Xr0zex0fWipnGzbrVYXmhMTcBvwUAsV3p4Agfh5ZmcPQI9NV70dpoy292XOjako5MkksHXfw1VDt5b0v45mNFtqqs3G6Io0LJ3hQtRNy9xGQfvcpUXEIza8XO9muqfJ9Qktzm5CQ13+6jctCIW9fotkpsZF2HTB/vgOw+ErvK3OzvVk5hJYlgdlTfDWGLN1ne8LMTSuOITisIfIZL12Outula+RUxu2ZyzJb9E+TBxlcKSaAlNl67HP4Z5aOqhkRS4aiPoCrftvNF7VprnG+VDPXJCx/WaTkyIFPcsj1/hQBpIWpEgBcEkoCh6ZhYaFVco5XVTGmc04RY6eOpy7pBmdWkvBcjYsE45Y+ityue0MsGaQ==
  template:
    metadata:
      name: work-delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
spec:
  encryptedData:
    pgpassword: AgBNoDTDmGvVykgb4zi7L3ozuMSxFhEujtVA9N9Mve3+XSrHhisGf7SEs0tZHfym7MMk7MzKHrKIubqMvMLLf/Ab9U+ctIfauYOFucGpSKvZyWmIvvKfTtAzSrbPV5TCvUsOG3nk0JNXm03HcEZHWkAS3z5sySnF3C78YKObqTnhccMKBSksiCbWmEX1ePB4QHNPz2OfrsFRjdWC0WxrjxPVmbdqST3HZHvGLpjwpONBmooum4j+mg+D75V3eHjgUYZ+2I3PzFi7wqwy1ORUO5GoYNQSI8+zy1f+qORNSMZtdmuE0IRus4ddI0uIznG47M8++2/TrhP926G7XGhIXSOuJtoAiqDVR82ylJukg9Woi9jWLFRfa2/MukWik8ajVj9b2PHYW/GhJRGQxIFswvpuGtXRMbGFr5WOwUJPIYlScxzPIpgq4dcqWlW9O2AOUcDB2Lp7NupX4flbwwOxlk64EjMqTi/w1TFE7DEPr1Gix4FO+aHXhCLKJv38H1wbTgR8irK/BrHNpaV1IZHRlkh2t+DAd5yFkOjBjYfng8PUp1BaPoJAeNPlrEbF7RkPE+tkV+UAHD1HLutZMNEeTB92wt+uFvat/IErDgchwqkV1/h+mtOlBuzb7b69xV28uMymZAhOAmzLPTbJ+uxexUe5HPe2jzZ/4uYFSo8e8tx2IsM13zZh5D4tYo7jNIAjCxiqCub4PEGgLLRPbc5mERrCi74MnbwjegL+OTr8RMQKZ/b3x02v7QG1
    tautullipassword: AgCg0Tgn88qJiBrVe6JamPUoZUu1INScFqv7Cda3AmpiY6W++1W4FfYCnv2Q/3r8eoF7qLQNa+kXjgR6Qn47WFgT0o8bzFmdMA429rGSe4FZ+kTCQ4LOtpBDj/mEZ38KlulsB3s4K6uForF1MFMhrB4KgcwaqWZEjs62BVGgORr3IkogtW0QOx4i042R1++XVF/xv50zoHEFPkDcam5vChHA/x/DgXVo3yeAjcNQzMsbF3qWBfeLggJuvpcHaWHJUE+Vmj9D+ur7MXj9yjZBMgabjn5nPwjlzl/e/LFO1ceu4DtXQ5Hy2/80rwbcc8QGAihCcFmHK+8iwTPJrwuK7K3Q9oU1aKhekpYXCK8YtQFCjdFU73Amn8GRDYy4oCehXBhcDenB0YkioBgkP/rwtDBpgaq/YEYmrF1KtASmOFKc9TXfCQQ3QRf8AidXtn3bShuVkiLJWDttM95yhHufsKNIn1BhP6qLU0rzF5uRNzpwQA78XiG56dUgQ5mOr2GKH8zW988ASKy7Q0b6strirclNj4Q820/7kzZqzfyDXOEEg1htZt16k+9bxICP2fub4Yz1YHvuWxVpr2vH7sbu5Ae1jN/KceJOhv4X85HV45k7pNB1oI+Yt0pGqWZUlb/orh7NbIYVLsTJfr5RLsIRH4QAJi9dYcMmf0yNkCB4T3DWXykoICX62rCsff9euOzSe8FcdTzE24VNZZFczZ1H/tgrlPhw6BKLPNMBypiiRQ81NA==
  template:
    metadata:
      name: survivor-tracker
      namespace: survivor-tracker
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgDOQ6yq/GSoSKbThDClu5HdfvdIuKMUoV0h4pzugDpuxDi3GTbi8JvZMIQVNZITwVDIj2T7N+5CMUULt4jr9q51lYjKm7WdcooIaKhjptBr9sq6mbnNFOgXb6MIi4V9sJRGqv0jFvb2J/iqWByqFksQJAgbisli7mcYxlceeO96Cd9MJ2yDpK3CwqGYAFafqejv1/+wNsqXNauOOzh54i7P498reFPOAhm+Zck6Ko0yX2ZqEMl8W80KocvoxehLd9WY8VXAnb8XrqqIDrcgKkSzAqhcrIty4HFUEyw7fYNKlY6VbxqnOwXpLGFI/SoTUcsFTR2285mmPbWDF45BCTq8hpujYKgf86X0jZ9+bZBTqVMJ1xpYih3t6lV481nmo1u1GiBP7jfy8V9bZU5mjoNRnRLDI4TPI5fNQy1tYsZDStGXAcHNDaLrOEHM+qlVnTkhN3dschhDECQEU+kDn6RyqMBUZJ/dNzgapDsHZ2pqxphJwBQzI33nvijX1MxX1yR01MoTdF7A1IBRRNYYgIpDE+p8X+ZJ2w9W8V+5BsEtTrGL/bfe+nXIwCt2ss6rNnlvaMOR3IdYmPU+9XaOykVSwSDQRvZXdXax91bGEc+tzmM3MtTQr5M1CjKSlzapLOuV9fVksTQjYlh8SCxwXXAJtthIG+MpBsTIfB9gdeHXNv0ogXaWmodL0cpKGri84J+3w63tetq1n6FsMlCZqjUTix8Qz3Lzt/2S669Qrd9YbDu3A0RlBXyLHeYX4B0c2D0Hcj/D7qk5rbRGp9lhV3xKdgdmGdmkNlUOra4BbmakVwod3Vqbv3MYjZjX/cKJNTkyV8ydqIw6oKE2klI4FNAxo752+Zry8isR4lM8G4i+TW+7fkb2nFwSb6hCfRtJfqYueGfhPob41NTcI7eQ27IbGv5xpRGIJiDnGkYF/53646tvdA==
  template:
    metadata:
      name: proxmox-cloud-controller-manager
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgB2r9fG/HUEHbKwUTDlOz3GFQdn0y5RoDgtBXGMChQDz6igy/DKFWG9g43xpXxjzcsHFwTJ/Q88/a/vyQNqQC1aI1/7SAVgflTgG1Xkx5LQC2QanFaH5qSjXvsvf5pSyOdntUP+JzGHDqSl6dEcaE38QgCCgx9gHHvK8iZz1y8JO8e7im/tFAFWXO7SFGjwSzh7PlcP1X8qY8VpdsJcsYKDadwsxjTzERMCCtvRpNxqe+2zJU786gkoIDApCscVRBZzOac/rY4Apn7dDKenEeS9jgLci/e6pZgL53SgeORZl0zDqM3y+2coApQxP+8OsiDqdkvVXBPV9RcPzF4Qq6bj8wpcx256urPaR9o6AW889geZjURqnSNix0cP87EPXZVDXHPhjzEvWIZNFA33TUES8xpwDgEuVkOnYvIuUG4xkiL8Y5SMMQTRJtE8JNiQpU49SV241mZXwjV1a343djyskt0LX5UtUJ3/H+AqhpuayTB1qXYLzXe/Lceqzkl/4U3mQ4LNM+eNsMimyEuHif+Kj2g1yynCTP+O+lbHLOFIE0Be0Q4kCfkeQKHOR8pte+afOpnO9Kp++a24ganN72ogNsRxMh4zIAJjUpl7lnF7Y8+mSTyfC0tJ0RBQldMys+vhwDkcXatup1E0+ANzdh3oSBKmIQL86Ms+Jk1CcNujcCmrcB2SaaBxRv/b9oFQ0sBgdeTPf6CEHAiYb5aaw5UGc9gLtP35Tde4d8WgeNDoco7iCQC4z2IuiOFZRCZNQ26iMuaLTLWqBHOVpuXGjs4DUPplPXXpf715uEafylIBLw6iVbq4hbvPttKb/XuTK32KTZvLXmzkWWM1jyvNJvFED59ISvLJcR9NsMSfaVF8xBRVm9v4A1NtH1f43WEtSih1AXydT5XbYi/16Exwj6qOVGXwppEVD5VqaZyNr2yBxCtBA8cAB1M=
  template:
    metadata:
      name: proxmox-csi
      namespace: csi-proxmox
    type: Opaque
