---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgBHUMo0sQCsgVvRQai/m6+yCdDX8pAj809KoakPm1FIgweWD5Gdb8U3W01oVO+0Pdo5dSGmx1UqkLh3oEH+qFfmohgO/1KNlQ4koIjUGBftATkkQiQtfFtXfauUVhoTlwsSTFvQKUM5xz1sHHpE+R/Z+Nr0JnpP4hbj/zilSD/wXJIzsnC/KJXG+vojBMuH94xwNnjbQUsCUvs25JLrfl1NumckCxf7brCjnkHBChj0zT7Q9MLV6TDzgA6cvhgAo2zAWeeGeYHjHC1nArG8+axK9vLVEOJxWcRCTysjTmTe5Qg9iF8iqhwVcUll1OuFO4e78VmS03JURpeBkYpUZ82oekjYoPVzVo8tGyML+gPamm4mGsnAxc20qxS+wpDcSpC8FKv3OfRA//4PWs/KF0ejdkBnaB0ZOHraeu7n1kvnECinkA3i9cTCdVHzRQJ5OyAX91CZD7lghaFX3F67DFvJ73D9njIv+L7DFZttLwPxYwqAWJKhvuBaN3wvGY7uaCoLZdv/a6B/UAPcQc02kjv1GPjfLPzGcQO+/dtYioxZPm8PMjFZVqzkIBlfcl7QxbI2CWnODDJgszXA+y7jZFR4jduxfQ/HuMdKnOzCl7HWZjWWxBCLXF4L/MHZXprhbKqCdrHtLe68Ge+XzoRwWCnq0M/y/vflcUzmQr2SlHYpiQ9+QN7HclTSynxoGq1HSHmwnQlhd9IXdA==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgC8neikPai7wT9PbTDakmVNnlWFjekmpRxIPTpmweL2GfYaAA0ah5F8XiKgPdOIYe+aRuqQ1CQm3vMZBndMhMzoCL1uxIQjjkfdS1YX/Dw9LvwRuINh+1v3jfdFqG9l2dz6DBuBssWXMnDkNHOeOXHdPZH53Oip6JPZ2NfPjHYHgFBOVwIHZReNd6srx7abV3UEEPTi6/MEm6fG11yaAUUpn+9fs7wZkxSKYyoz+44Osq83Bjc+Y2HBGjYS9A8c/PYTPN03PEJK9h7gge3UFU1KJKXKZplx6J4Id7G5WlFfAzHoaBXCLObFyc2AUXMZdEzz1ZuD+L7QTo1btHgeajAdi96WfEQxEwZa7ad7kieb7RbEuQY/8bauJMHLZWITCDDd+DFtCsFQH3ECT3c9u8kS21HMge+sOCKC5CTCcom4M8iio9iXv6fXj9L6HIIhyg7F/YoE47yJ69twG/WR0vaE71Vx4xHnXqxnGEXw/FEKkH11+dWnqowxWJfunmGkpLTZCvMiBXpLKuqDTJZyo1IIlwsKTKr0PoLlEEdrI/Ik/05JQxdcvWRqFtpMTz6bKXJnTRLYmXgdI/yEcPOjvE+s1hE8QyJEhYrelZUeduAvuJVNPhh1YNUs4ST9sOJeMj/o8WzZuc8ir5DBB/QVv7pYrpkOQGGgSLD3mukr1SPq7Tc0BslgnSDrTIXfhUHVljFvTGzTUUDJztM=
    AWS_ENDPOINTS: AgB+rs5RyKHDiJDHEdnNgwM7dmhPim9FMWdO5rUA9KbTohNX/+bRMRIddWtisq4GVH+/AK3DdP//FkE/pyBW2W/lAw2aWDRzS6dxV97+/7fbjrs2rT1KDpflh+jKkPalAsflM3rwDThJbQOgp/aTinKLYpU+ngdcxP0qQNzVr5NYsMszlhh8gfhKqam2ZxnnG3JZbY7Vj5ncyh23nVsAnwSu+wgpWA3TsQ87bInWzW08DpLqE2JkVwZ4l2Eg2WYfc4PaIpzei2puANFYVjeI+3ppOm6UEbA/ROp8vY65Spe4RV7PchoESvR36HSdHkfI3AMaZQQeSZrQRmzT2X6e8dfUZFB1tmkvgYZiVd7xcpYITBdu15diCQiiecBWd+9paR28unTI/6oofY1GmDJU6fSDNCTO7yXgFfEgqSBafphGLgJNPDSvHdR+rAE9tpidpw+fUHXNdTHu08MXyCXuMXhtF8NPjLu3M+nvl8WpKnmCAYdg+ho9Hx0CLyT4PnWVPlHiH+Xh7hO/SXXm91GUFb6gMLUgv7VnbI2/pS674yIbVUQ34baL1yz6HIzRYUyvg7MyU+pnJrd1JReCqtFMNMXnpnqeZAPMQSnnuixJisNM1wQjPvyeV70d4notbXr9nzaCZOXfvw3mo5P7TnSBQMc3RxClM5r/+54s6qEXy/j9A8LcXW+kCpmQHWEUdNqeej0KRcOYTFYmdiV9uPLamtwnWDTlzWLIooH/qQ==
    AWS_SECRET_ACCESS_KEY: AgB5MBuK8y5X/hWT2KatZwIjmvFEDlehwNH6OrPDW5xHQD+bNilr/X7d/0uMgFls7DNvvY3wPJcq0SKsZzYWfjUAsqVUXqEvUmbFKmSJGa+E29qwiI7JFBlpIwbbqteamP4ZUMCbQimm/vj7qnny3kJjP7DmUVjmEEhMduxDadLjqIpbODPMwvuitEb1waB2FRfslgZUmCiP6GC/44yRVodSVOf34P1PwxHgAFxG2Gynp1LQT+kqCMcBd/NbI1BuXkwxW9TdePvYMHjMECCq9/sc5YkecQHfkARqDAa8RXb6TuXgw0R5MZ0oKg6RSahIQSkQK/Hvn+T35/6ZdSFp940QPXla0DasW51cBUPU2TwMZc+nrhvB82RnUEfr0TGSf1uxb+EqeY5MXoq747ACwJFbOOORiFtQlr1fOMIYBit4sxH0jiaeM1HDHt3w2SJY20PDznnXVW4RvPwuakBOB7a/X79t67LIQUiSV7k9fD2K2Xdhrkz+V/DVE9jNXBk13r9s9l4S22+SyzqmsobQV3K9GyuZO4aexKrhhWHIVhyAnCLkvbg7SYjSGdluU07rTDl+/EqeBV0mY4p2misVpM94I5S1vxCqMb/6uGe3HWaf39ZzLBa1CFzHa8VA+BCDjJOpzH6KPHbrz3igFiBTiSfa67SgIFo0CXeQhrSQh5LW0u0Ec6S3uYpyOZ05pL/mB9GBcEGq+kjAMlMEaigTSENqbaN9HtE1/vSykoACfMfTsNmtFFJDeAZa
  template:
    metadata:
      name: minio
      namespace: longhorn-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAd8VtBiIDt8mU7s9E7a5nXtnWsaESulA0sv8kRlxY3ZJaS+fAtVkMiP1mPC0xL6wAPExwNPiHz8pO3ziPbxKa9NWQskvy/60zmIZwN7IhKnSOmPPXV1J31F3U3LTCnl9WP38ZS5jOlSpLpNxGG0Br+pEuci5wnadLtbFqMsoivh4sx4pWsX+paYBeh23p8aX3FQx8fhKl1t+hZPH5wa8FheHtQE0XVvvDUgAoMhc8PjZFW0Hb3iOsxJwzP2cgdBWDL05gkoVM3Kfa5N3RiperkTFud1a1NpJR6LmIi+9V3rhOIbSjQ+4HEs+toOGqpNdycXArFInQmGwnThak2Qf3SuVikmfnjzjb5VNeH1fW9KMxj3gJJwCf7i8d5EbvxCcydjZlU9p/LwPzPuFEKqtHy2KkHsaZXLrVXi1J4xbNVCZlVe2LQ8oxzRKnyQfoGlxD1jIMhzayB4mvjLbWiIjjC6zMcjGiS9TgUPTDnQw0T5xxtLAZr2LneMgscJp2U57JBLbb+CDatlkOZaLOY9hMfFsOs07yOfyHIkjIHnNbntvlTtnotfPB2Gnhd/OJrymm4TDeI8xZ/lzjAqMBBXaf93aUOjvjz5rHM7DoY4ReKZHzK5MYOpULlqsVfbzS/WoocONXLjMHCM3ljoUzUL6XITlK0RxXr85/ZTfsa7geWxji378I8QqrCfyigaFYyYU7i2mug8B1i5Dr8DWlNFeu8cg==
    client_secret: AgB9Aj6WYuOTcP0rkCnxmQXJKbRBP+MCFJelEs5GWJyy2JGidh0vlltKAOGVl5RGA8X/ih8uKgX/Qwat4n2R/DP2BrX0CxzPlOkokKf+gk/TLFh+hEXwqEWcaed5XZCwBDtQ4b2aXn1sdpZVfse6kHSGZCVnkaYcGz3h5qDEpn0OqODkRjCJ73q0LdaI/dD0Z0M0RTXEecSu0SwOOwDZlnwOf7MK4rH4fqXECl7MnFTkHcTQnE6fYBG5rDaF3sPNvZY7bL1RXiFxTrM2YZe/HoMAFifpnZnHNqwyTyuOel0tEb43hlwqOcTsGUyCMlYVe+7/sG5u/A50kX3Uee+hl9SAY2Y6xFlrimu015BqnWmrs6XIX5aSvI2oz9kja0GpfyIg0V1S5LM+P7Na7AfN5JNHvZ8F1xvjeF9ILcN8wtjp0na0rX7Sxwy9w44qaeuKmdf8aHaDQdppNNX3xjUQjEirmLjfQQ3EtSM2WpBD4AuBjEVw5KGJclS66F1ndQoNCKmHWbBVzroG6cINHYt/qRWr4AkQx3FEc9ClDXU6YpBcxDF5PjtJohmWPvHhUfriBiXdoz5JGAJ+No7THyiwqfJEk3Ekf66ojpciapsaKKJ8sPBs09wwc52RWo8nC9qQYgSKzkTi5QDu/24uS7Nn69ACHEZNv+Or6xOjC9EVU/HGfimIB8jbr0XDktiwFjba/9qx37oDR5ZOMP2T0lGmEOZa1UmhB9pyb8NLLZObMeOwkauY+o7BhBB+jYncHXnuq8Jyxs+okxtq0CrKukS8T/U=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgA0dZ0cIspf4c1Y6OW/wd2cUAwT9P19SJCdKlY0i2JtO3mxyQffb+OCVRa76qYaSZ+1olYeIiU79IbT4mFl8mRrGPvP9TKLjgHGNVVAkvDdX+ty8XOygNzhOw9RD1mRj24Zev/mqhfi5fKRKU4iSKRmcJTZxZ/KwqiX9hgPe3De/s5fkhoXf6xiNB/0X/GFq4ASH2TKw2bn2SYqAa6fKY8DxnsBesDMSCBPdQKhFVilTsE0afhSzDho65st+R9TfgSM4RgrN2Zsrde5WWHaWkuivk85LbJsiunCdR9Vns7vE/HOY7Ai4NTdJFGiT9fu3Rpii9TpsCjQdr80QQR7PaSPCH5Z6uguv3mmboEu5VRsWz3JOdEiQl1n37KM+jWngQpJvImre6WSxM9cDBLIi6/R54ahCzio9YjP7Wq4Lwykh32BGfClNzLPwCklAXbJDNnHEeX9A/urzUyg2UqxWLIkOUX9WnKizcUfnibpbFlZ9NTrXbLV4ZP46LChW+vObEIbEgl0vBAsbpYxTbAzrLyn7wW/VeQi/cbjtcKDOX+o+DuicTRrvnn4KGsMoOaONVNJ6UQaL7CYVdQ4xkhE7g2pErgl9FL1il8AH9E0ufvxdtWBF9BbAP5G2t5VlPqWc2be1X8A0WblzA8jkuA21l4J3myeIloCX75kITq3cPWpjXBesjVHh9LvMPm+nBrxBLFZObCF/z2439PNq8qw/W11FQ5oI6ujd+QA1rSaFNOK+iV/3G+QTbi7BY1QTg==
  template:
    metadata:
      name: delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: work-delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgBMWmjbmiY3yJ8budZGvosYQfnUK/tSL3rejQPFUMZYBaYiHclQkLh9Y8P3WSrc3FzBGgrhEzEo+aw/PA+vFVjn5E41zKkUh62z1YeUJmsUT8OAyt3KrDYJyb/MHFaaeJzvoY6zJT8yu55ZQRUX8zVVAmMehdzHnX6Hh03UM/puGs/PgCf1VDYSIpVgRbOd1Pug2hnf5H72tCCMECKIiEAI3RqHWkM+uC946rzHqxyWHLq0pSjNzTtNk/5bXSZAPYbm8/gPcKSFxLD9BTjuQ3/zXxYI4qG4X9tw2HjXtqTEyiGmQnU3eJT+l8tIREzWsXQMTCIWRRVsOQvW5QqZ8q34oh1Cf8PdeCn+xtOON/DTTwmo2mXbzveA/RM9YUPflaHo/lJ8OnztAn+Ei/D+Nawm5MIvHJrQgN0fRsboavwD93EZlxI7NA4dkZwVREuRwnT8mZ+33yTC+aspDHGP0oBtb57AsnhHD0o+ygpPe1hgApKdPppNHgJHMtpryTescoWxR2LGVUlCrurdkchIRcg6S3zg/0nwpGGHAWHJ1OsLgjbM+zFqAAGvBrlfVoYmuHwtyewNDhlVZlLG3QPk6x7SR/dCShsOBkkWKLqD4qIcf+0e/bMquvspnrsgjtZL7HHju4pXigP4xHaKndZj1iY+xNSebm8/oxMfQqINXTIOc6ZSU9cx2MTPo1QQk8UUwVsVAevMx67pxaPRnevX2890IyHUKQStrkTri3mMvk2ie5HygIGJ3Fr+FDXBJg==
  template:
    metadata:
      name: work-delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
spec:
  encryptedData:
    pgpassword: AgBhl0n6b/Hivob7kVq/4c+xJrN7Y9a77GJRCNGyQvzIw5dU4luMC2z+mkpxSM04hlXwJfNeU2tlHKlFbNMOM3ODCfEiZAxVaCJy/1XvWDuf9tQ5JmM3iJORkU+hhxkxcIHVQEQ6pqijmntVNzvfhlqOePfa+NpFV4c7RhfUiYEQnT6JrI+mkv5yvI3M945ex2WXDHFn3wHKPfxFZceHx39BhmT41FNBsHkh1MDCGhTj4ZPJ+JGd/5eEjO+cvdBfB6NEcLSks5DFKVYdZCANYoHWTVwpW+AVzUK4cbhaQqnjREwMcdlrVBqA/UF1c39QR687Xc0alFlhpjUFtsFwau7SpvBoIci7AYt7CpY9Hqt1+kYC0xkUGYsZAjcGldQza7BZRj48ySnKo7KLIU/2AX66Gc3mxf3JV2sPHyVSzcaxKNOwSFh1k5B5l4Lhfk2kGjOIEq6eh/YonnzCpS6sHXlktaj5N/RwLyCRH/0mh5rYrBLcXML1c8ZPGXkOY9rMRbHeKW8o1nuRfhMdQZ/vO4enV5m4dP0Erhu7EyBb90g62mG7Xi3+EkXcD8AHcM3rthIHrZz/VzG65XhXkxQ3kPc7SjoWHWfVJkqosceMOPM50ibjeTg1NwqamaOaBoFny2k9k33b5CNGYBFsPMN79MsgCQZjd57stU8yXYrneXbwnbDPwq95ENSTCimZ8tO2BPmU12KWORVJdxmiBSIKyh9yeuhf5Q5vnsT7d1i7wr2HJWrFNYPIC9Jg
    tautullipassword: AgAsAqHHiOAYrjvMAQ5ugAsjeTSXBppUpvDl+vNG729Kbb3nEBimSqmnG6yy64cfdWXQia5v7n5KuKPWyCqR7MV3vgmFN3zTawv7SiQl1IDgc696wBLVqoqc3wuaGlUMu/539Kq7XO+2yaxA70cXJBiaYUgK+fkt+838Uwzpu6Mlc6qoAA63w7PhYt6ZwzMNKoZebnau8VBdM2ij2Ke9PhH7jl7smt/dmJw9I2ag60rR2owvOLmiSw6Nc6su+4kAcVnbseC5/wU5/vC4pAq01aolyzkDltdIfP0Pg6WTDCDH/T2ymSw7ugZ+sFKRYBF5X8gwMmUCzCt0KD6q3bn7DOOPmW7H60nkS7ORaZGIXychczoKB4IhDBiP9/C47blmJNDEuAMjRzA0sr9caieSUFAvELF+IyvXQHa4GLsCGohyo7lXJvnRilTIKXBjxH8mP5zzDaPbRBakJeUVUsRPgCo0hIkpxHftd8JesHUhI7btICRnSpxTmaG9ZlP+yfxRO9YJtzE1V4vitNgb1FV24u7vPWkqKrrHVUKlyhN0DqKVMsLjl6Mjh/vewegPXY3OQUkg4eI36xxCr2nrKiAtbRJa6QF6u4QhbVXocMDUfZFUKUo5r9TX1JT8npjXgYd+m/Wu6BF9scQ9lJNU4+gF502Ig2mBqgvB54o6sZrx3fAThUxW8S1IL2MKJvjMjMrygEuBcEeK+aKMsWFrGVUCitULgSaSJVZRAAbSH9P1iJvHtw==
  template:
    metadata:
      name: survivor-tracker
      namespace: survivor-tracker
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgAISauZ+SIrjhysK3jw7qNufgqxVA1ENXx5+8H3od6fEYY1DB3IUUhqcasZFfQnCBo77rsLwiqqbQgVcnAyZKioC2q2jDnIuH9l/D919sIwADiRc+mH/mnwwzkh+bVeXo3NqkjA9fd72REbEc0dgbNgliODqmW73QntDHmrjW2r6hw9VKhaFKlcWzwtzdDFcLziYH1QU53Yo6iFl999RT3or+EN9Oy9EVzGltZstAl72STJlEDzINivEbvZU8tH05e/7rJErVjMhVU2wlydRd/WalkM6ElzTuSGRN26pE7UHTSauKv5eGgcoLw+Kz7UuT7OA81kINsq2oKWAm1BlDOveaLCM07mrQlNl2JHF7UM6w+VoMVjI2Eus4nNGQDdC3mxaJ5V0xc8+18vYn3B03Es3+i7TweqP9VAzLDckVXvxF1A7ZBmZ5fCcgNzuHSXTd8gwGDbek6kzfSGJOPZDzqwWCTFYpJgNovMdIPDzWHuaaYblgwNqpnwbRCTWCIwvbQk0xCASXvDZhIGVYKv8Es04HSwrZoseZkerZnTmelilP2l0giXk/evOTdyYCLMLC8Bboq52uE9l2uxzSLKLE86rjaXb1SvuSA806mqnj1KPBniEr5QejTFxUCBX0wfW/6Jq0Cy5a13iVyuEsBiVLt7ExEL8GAp6xNdtPzKpSSqAFkVrX3IGoc5k0NpZxK9gknqnm6nKF3K/8GaiBb7ooxH+eL9jagLWMDZDWbZ7CukkBe3pxvgeXlc8DZ1/VejxYsO30LcgrXYSDyHve1FXsizwTsyCI82ESMqUQv/PXKJVl0iyBXBXwingRGwQG2AWqR3A+0WDqQiHK93PRRZsCqUkNyGhVZy7AHqtP7QWuk+pZbUyQ2/xQ4CUoMvD2K74BNjFwL+MLULRJl7SbjMg6pbz/ifyuNeRo1ltbzTKiyX30rmwA==
  template:
    metadata:
      name: proxmox-cloud-controller-manager
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgAduTXHIAyYBSIoAIBkEG9mUy8C3xMFAF6+gISOHkOeN+QaS7/rsiyoZG7i0a/zzP0G6myx+tdqCclTdy8eKdw4mttQK/g9ePlMEIhuYoAwcjVZU2Xdbd954ha8814XQFZLq/NhtbarfyzFk3+oqRsU7My1IDSDRRgLB8k1rmoi4ULpgXk9KNrSKpiseL9RkKrqKYm1ui7yswi6KE4DECMu+ZLblwDbe828GXPK0XCZBtYvSebNgUVwqmszjs/Br16QKjXA3ZonmAqAXtgT5Sk74221sVQnd0YA50FkPRkhp2vTijXEkC1PQD2LJZUFH1aub8fcff7tt7Syfcy5nVXvKSz/spgIYMe4b3MhTOziovvbiaz6MjEv06yj8sVw9qGRtqMzwQkgjdnIXVZQRRbRgHBPMLasEnuMUliNKcX+ZYsRQq8sVDTRIEzDudoBqmBuJ3hx5hzVFHbfe/qvXjbbCt/KH7lVttNmZjXr4uQdt1eRGUT5YttibC1g0pppCeffE1s58vRJRkd1ROMr7doe/FPdI5eVR25pcUjOJ7MqFfY18EnADjxkylvPPRMcqHHkdc3yVAS4RgMAhLA5n/4QCERlriwdHzqgsCBMeHNRLugd4MvP/k106jClU1puiFm9m+dIWXWH16/u1JQSOTMOyEwR/7zE+WykdyK+ECmGAsSLH3FPVguyCQmJ10y0yPW3xu2ziAnL1wz1UUYm7E8/4McIOCHQhKL3xH3kfA8W+xOTDvCxVNEuvE9wjiyrxr/XmwiNFLj63I8/bXb6ju6qiGjTJuMdQD6MhwXbpDWzYjtrSPuHP31oW9/VMTIxQ3ztdF38uX1G9+0EmUwzry6I3OSyRkCRp6d81SWRJEjiF9aLdw5rEwJj6X4qJBrKur4cfoV7qzM3Ixrb3/Ha4DFHkvRPQCHWv1hDpf9SkeA8mMfF49C7iMU=
  template:
    metadata:
      name: proxmox-csi
      namespace: csi-proxmox
    type: Opaque
