---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCS7kOfF1PEwhV+lng4id2IeihUyw+7y2n+mRTEH44uvyRWEinVfQ4CXTIA1BgE1GfKUA1oCytDtRwW4SEAuq9c423MXNlfTtBbBm1YySBUb1WFIxmgBt2489de32VDe0gB7v9i2fXIXp/oH18+0wzh+fsV4yzSZy7y/D7o+96rRB1YeCLcBOMcI5YMRpGPfN4lJdl20dLUYYBFx+S3s38796F6H74LP8V+H0YTtj4OriwzFGzw8S9VfcoGn8cNtCr4uF2b3svneOeJY4sJ2CbtpfhLXZemUXRwciNRPxgCZKYVIDgF2bTL2sdS8RrvlESgxNDpfCq2kH9BWhu9Zz5MYLI7OjUnvpTYp4Rt+uMAhwo/SLiljip/akll8efUlCp+1qpV7pD08xEyp+aw47qKbRex3Pv3VdeeVGRFo55WB7sNIZJk9OFwWBOll4CwTI78vuD2LVrRDsuVkYs4v1OWzUGrbJz52dSSy7mwiHCP7pd71Ywht2rIX2yTopd0f+zUKrN+X3hI52dlc8ZB8C+OebFUltTIkdGj4Xf1JTJdMKQkb/mfw1SZODC/6F092CXcuSHUtvzB+vMyVnhp8kDckQpKg4hE38LiQhOOcFEEQb/BVO4BL+nc86oc7iqw5tQZP4FdQJoIDuVxkgxdEpfMhx4QRrQ0a56KyZgbqsXgGSz4PwsGo6sqlbi/xVsCRSkOyBPB+K5lcQ==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBusdRjoqpItWUw9jcUeNvJke9gQLRKd6jJKkeCDixYfNZQd3fBChj/mJrtR9MFrAAON/4kUNs6G2BgEZXsIy6bpRMDfDGTBE0+ttaiRDLd5I+qJI/p+6g1UMuXIdC+SeLI9zIkFQRqQdKX7X2b37z/YT3UL+JcWGLcW7XlqtyPxLwhiClOK+rRROIAeSU/djvpQMVo8dUQHLtTWDMmZa45S5N689748i5OSumd1mrPuhYJTnSYmrVtleIXqHefkpKVJpvOGAPZmT1xfoFYGh7erlBv/BfvWf/m2J1b9qT4kcGxCtHPuQd/fQk2ydvLgmN8hEVl6GpCm5dgMGq/r+hKg+j8ROQqNd9nS18xSMDMNpwZRg/U5UURXWqVbx/36CQVbSeNdhYPQTI6TjS6y4ZusmyMCcb6UzDOTpP+AonbWBgtnTOhqCaf3SW6gEV+k38WmwxK0FgUPT6NtdLxz6HsrkF4LHuaEob91o1u1HULp/z39TY+FRd3Tqrh2xbJcZnVdqOwABOzwMiMxJnLinueRFnhgMHr41s27XGHMp7oOmt+cVRJtBUKWsKW3TZTkWMyLnziBHKOX7el1aIQ9fEJJicXfPBKfMaTqAYYEpxc9+CQWwhgw8tU179Vjx2R12ntTdHrqAXVOlGdSp0rfa3f31XykIGdzRwj7nOXAQiSpHkWypkcAhAVnasXLQj6yfPugez9DY2ReAL61qTHniIWVQ==
    client_secret: AgCc40t44GF0S/OdyqvWvD951or4f3ULUYhNpSQ8BfM4IaDpBLOKyszpxceuGPdO8A5gO8PnQ6y3gf2w4pJizUgUTgm54MfiIUcUB1MTI79alFukJyW/5gMNaiQ84DxkA37GfYWIi9FlmlLhT20jMJr7e7SWq4LV5/DJlRZMEp2Vi+XREc8hdFsPs8SdqP677FE9inhf7T8+czSRNj7Rgg6JxedmA3JDB0M2nU9q7IjhsHgvYR8uO9qQfmtM4Y+YOJAYa8vDu24G42TgjvHbMliQI1iyg0qE/BXtWTGfZDCcx2oGFyZ3+HlmcEnlT4vQqDh1yBx+bDcWYfZT1BtoGlunJ5xjxVKjvCm1rBjtHWcH9KgVnxTxyyP0NLYX8XASq2s3kvgA/Myr6zAbmZr4M/9hzsrQfz35Gz7ER7D6qGIafuN4zohlvtgiLqN5tUehvr4+p0mJ8+UPihh6aBzHoVhkiqNsBMQudmUpjZw3MuqlYQUzxkKm54DEItXdaZhsRHBstLkFjj1NNM31PI+u4Tgbx5mMG4lG/JT0mtBOdMv0ZA/endY/i0z2HPawi1WLDKTlBRpISZMCYuCT3bknjiEyD/5bMvVkemAOnrtQVo2Qfq+kDl5pfy/FcbKXnVttvsiLftHmyYgamqwoSvK7HjNs2Iwn8FQNfqHEjkl39S13DCzPDC/yWJEFiOUt9fZAaKj3XVhWkXi7EvySelvN/Y+cc/0Z2q2Zcor4MdyhQlyLZgedrEi83BiZsvbD3Y5vP6Malxk2O1mvSZYjf0GjArU=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgAzmhSQ4VYqKOw0pryu2GveEdUhbwDPbhzloBdf+KrXBpS2jiP2LcTUEEfS1xZmjW9fL2VBFgu6ujmnG5Uy2yQqkjg8W9TdO87e71iGC2ZyEpmTKFF+Ua07calgCDLPGtgXk/OP5dAX4TQWyGb7zQu62u4L+kKJ6zfPJMykfbI9ThqhnNseLV7GpS0LU00CM4U9PvCfpIRZPBzcInEnBhulcaaq7tmDFjmBDrhaXOQEEADwe4C1z0jWgTvvn1ojidYxMGhbTEJmQHrmujpSD/v/HBRErp+fEinpH/zFI5y1J4Cn9pmYcBsPd/cTYOSpQNcUz+tNHqQjdu8ZL1XleBoT0Cc/rwYzmTXfbQfehMyPmyxAMu3lhI1diyoLiB53G0Vnr0hgRduxHp3gw9NMlwVwaFizagPY0RdC3Uw51nqCFEJ0lmNmi9pN3AhpD7oLXaPsvkqJk4kSLVBIAE/Ckdg3RDImfkiBJdZ3dX0LtfIazBQhmq5hR4LLOpalxkr9jOuAnu7oerVLiEIwIcV8ARoZQ8CFZEasUrmAUVLl4obrxmJTdhXwMHHZ9DtRd+ANapS6FjOd468ZUbj5vf5BNt/nu7CcXD5XsfoA+4evd9pfcfVG5TqOKaYxFXQdh6aboyEJWCSXgWH/0D7537eSCCDFNVS/+ilLqR6YkAXSuIsubTB3l9C181jKq62HtMRs1GyY0cyC6lMvspBhAIf8dpp9q5K7hwyrSMGIDcF6aokRXT+ux6RVvIvM3JEfQw==
  template:
    metadata:
      name: delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: work-delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgAvRV73WJwNjvu5jsiKncIJzcDqBsTGcJhx+m4VX/U7omgG8osA/tVBON4TmC75GlXXPhUkxvdYDnLEmMGD6X9OF9P+4L6ALqee08+qpCbUtzBTEiKnBC+Ud9v5kKVfcI6Mh358+C4XYfUIB6F1Pv9uaGKieiDpp5Z3lJhP15Zy6XnbVtEVtilQW0WArUgPKMAbZniYm7G6xWZKLt0fk9ufMkRwAPNRDTD+zODzZcwX2V41UakiT56f94cl9nQ3bVODRT+zLXkXloWoqS9bAirR1NnUO4z10wxIMqEn3My7Vq1jjzcCptql2A70D87jfkEQJX1jNhhF7P4pb4c3bfUS19pRnxE6eBhYoxqrqSWT8pwv2ySY3WTzKfNyx9mEeaZs+YpM5Ad+0zk7WelQXqCNikselHK2l4EVm/0Qism3B5Mll3Y/YuOybCSgq2tdB/bbzwFyMh22+SHD2nwRU5gwhb1ME6TpYMuG/XYVOyJBG56HpXYXLUEC2uUCZxoBalAuNiaHVprK91hhSvBddgSeiBrVkKVcovb3NKunyMQlgkBZ12r4O42cGVfxcLgKYuboiRi0WPovJ36sQ6jFCOKjiCeb3+Aurc9L1r9WUdQrZVG99vO5p9ijFvbdlmelgymVvQsky48grLfszIAWkvJktTwfirRQ4aL3Bc3SFwWdTsnlzK0w+I1zm/SxFw6ldLkr0LZQcfGYcvPaeUwdN1PSZWsd5V4qZW5euN2UigJ70br1Cfv5CDcSSzYLmA==
  template:
    metadata:
      name: work-delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: work-shared-delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgAFz7v10iPPl6poXz1OxUXyPecYvlW3Q6qH+FWAJnr7q0U8RLKkoHiQT4tOp7xZ6ZYTAFjHYuy1t6g9Dowb7vnrKDsgZxIrCC5upLT9WZbpPW3/fKKMxq6BXChtg8KT0x6nFQ4Ec8BwcwqospRXEO8o1IYyjm8xjkEPMKwUabpDe0s0mOmgc45sPplFW0dlS5E73yo/DXgX1XHgMcptdF/V6OfpwTh7kdcsE6pyrBFeBj8G1YN0qQCGSK+91kYzNL+yYjRTeMD5fwi0dQTgavRgJbgQMMPydjT4at9s+OLUinBHkIaNT7o96PHgy7MySvv5bVYit+EeT0qKSyiE0E9pW3jJKqpYws3JkPVisCdxZw6Elb+GpqdThhDGSFZWtrKca3ISwkug/XM+i/bfMeitNyB7xXGp0VybMRcKgJuEnRyUgvyGr5w/kgG7C9+lHjOhAj0bV44mievp9lP8j5JjH/nWMmGXwHgbvJCH0PJsz5QnX4oFWsZ4VFXXEl7zP0nwr/d6022NgcrMMkNUf5P2V+/icHf/gMAynYnVWxAiZpBFk4520SdqCX04/+TVu05gOonC+ByiZWB1sak5zVW7Jaz17YX4uSvYVqbNE4rMu+cl7+YUaPYW2T3UsevWcm71ZV3/txbwyx9PJgY582BVJZMZJpTIQY184Xq59D453OMN0opHaD2cYAC/A9zfreqVk3w9dX/vK6c/9YseoYvtzHvQP6qwvDW5huuQO7v19Ext8uDorRAnxQ3RaQ==
  template:
    metadata:
      name: work-shared-delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
spec:
  encryptedData:
    pgpassword: AgDNtjc73BL7yBvXHrir1T3PzbqgTPNfqUhSYmur/PagN0IyhQkBIurctTRtfQUiwvQbkf8Yac3IZiSMBNyV9A8n8wmBx844CIy6Kw2ACz0doZksJoFQ9AAJO8N4w8HhSYyj1jS2nn0Ttw30dNLovA8a3nr67womBvO/IuJKpccOe00J+eCVguzy0wpUw2FdFJALJKG0cdbe31ufKuUjWPmvqqQUI6Wy3SaLYHB+UOEXSROI1hD0fozQG/CES/k8qL58E0vceYeCc11lhbYkORskpHa3d4SCaNfSqg8vZr+/GQ3S4ukxQMy+YjY4a6+RZ8mbz8Bctfu8RtA/VnoyZ3ZdMwGtrI49bXlriCEBeNjWZdwG302MXOWIkqKTQkNk/V9ITtUW7ki7FoZKP0B4lGpx2C2IYgP3yW/FvvhUasOk/F2KsYWajFY4nCNFew2SmRXVEsleYxOZCYbYa3GxKrxFBCIWW2KfWpPxQWAFZCMZO3cDdnl+vGXML/zgfK+JD0OF6aYgP3CqzaJxV96jfgRMDgJ2h4q8pUdIiuX3scVTP6M4UrEYqvR1XA0BGtO7Tw1ruy+uhgX/bZeymQDKzrX9ymUfRhclVwxns/3GghD8Rt2aWyofNg8VU//nBwPIB6elqe9BFA3VfQUs5xhIvYmV+x2UAAk2DGyNNReOBrAie+5wZo+/5iwINui7VlRF1NKWUEg7/vY9Svl4Upn/fCqxHV48It86LcTgpXSnmSPqUf1WdIUUX35/
    tautullipassword: AgCrpctT8bVCOrSEYzp4bjCZykPJ5WBfoellM/No5NsNKs4+9uflWRhMx6xG/rxTkkXUYRYkwV1PJSZr0I3Oav87duQJOpvHOc+vC5R3aMENqbK23l4UMToY05s3+noSqSWT9pmmmrtLKjX/cI7pE/6RbcMw8mR3BB+WN7b/MEjLFg4BmqPVKIgQEciPsoaxqZlfpFpxpPYLeoykL87NPyTz6p39b8QgWbWB9fWDWj8L2CZuLUw4VAJJHRGv+oZgFNGHnaiOuShukQ1SSQVjKcKTa7XUrkxmZYEt4w0lmUjZ69heC84buU2PvtsDbY9yVrM+NFoKY6wTPrzxLnY/dYcaJysYkY2EEp2N+NmQE8PHLQzTP/OTpuM4h440QaDhevutoq2ZTLXVSFhWaY1yUp39y1axlIswnZBXjzKNPi0P2p0qQfo4pOAPww780RFuVFaMufKGEE4mgAXjwlMl1SfI2M1sHXty51AIZDPDoWDOrS5vZZFLtRgf6w7Y0xPsTCE26rAc/8Zp2GfxYOf4nJEU8wJCOBNn9L7IkXpBpn5dp05uUhDA/6MJdXrgLSW7UJAO0RVhLR9qvWaIiqRDt2M+LFJirDPiu3wLwa2qm3w7ZkNl+Hoa/s0E/2ObINozu6LZp2VEziHhGEaEI8pNDBJeV9S78Bl1xiFN9klXvYYjM3lNjOSjQKe8yfdx622QQTJyf+BLDFj4T8vKzy1F/noPsmMEozTipqJ814mQt2GJ5g==
  template:
    metadata:
      name: survivor-tracker
      namespace: survivor-tracker
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgCoqIWfH5lHSQuefMmJ/Gk5g5ZYPyW5TYpBgncdWi6xLuchWXfoYI4nTLyhlwUTqOF2oad4hUnO5xJDEIMYd+hryyh9GcXqfug8mossm/3KQxgYSJzhYiPwioQjWRwbJpFa4yI5IZ63qcYEsG6goq+MSRLg4b7HwHvXBp5h5pTsFE+91cR6shmbF0AUakc0MgNVtrq3dCZB/nKmUat1YOANZoYAM44cNhS9c6tF6mpI/s859MjnokREpwWan91+c/d48aZWYpgNZLdxSKetSmvRJPRmhdaSa1uXjSH5a6rm9AMw0UL1b1qSENJzrABTiztCTzETDoZqaRWF6hdKI1t9fuZdofjcyDa9NOpBNW0n1UXZzvIWtzuoj3vmN6slPjqprBeeHm7bx124nigzOcD9FrTP2Dt1hu9f9oqqRKLFwRAZzph6dTIVsWNbedZPjfkZQ5hmVOyHUFtD3060yU66iZbZGDIs+slADAZ0qWg1UUC8rsZ2klRphKObtRn9/5GCYLMRbjyeO6CiN73e5lWLbORtS5qoxK2VSJcfMz1vEs26pt8nrHQwvCSCXSgl3YEWKFL5Y9Mce6tdjvYBfVHMNVjEi9VuF9lWE7t/u8UXkLKCurSZt6F1pDzz5lWxOrsmgCMvwk/VuRpg2qoqyFLftzAkhkHINmh+sQeCOWbuokP6/FfmTEBaRNW3EcZUZwnQ8C7dcxLrIsIa0zhhxvw9jWENl26YFsdT/PH5J6rXA/iaetbQpZ8j0OQMFubnEPfyeYeQorHKFSERzetsJyBNQLoSJxWXGL2zmTHDtQ5dQzh4+inVgBeRT0TRuqJNQaTQIzE2YyRy1bUX6F8xAgqCDFc+9iMrZRuZKQox8Hpv01qns/g7pKCCF1oKGQQRlqwo4i7vOm/Z3zEag8BXoGPhE7hSFRZPDA/r5qoh1ajBnB17Pg==
  template:
    metadata:
      name: proxmox-cloud-controller-manager
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgAVwMI7bqTl8kaIKfUm9xzQcTuUoa/caug26+I98KjHjmR6VsL5d9TOVvsc4sO+X2reKYp9NG6WFPipTvOrkqKjp4NIcypc/o7yCIJDzR+ZeP0S18R0HaKaCAQfk3kJ3LI5bqqFB1zNS1u0MDDC0q6OJsWtOoaJRLgD/78pgw8wZH5KmfJUvteoBghn9aTuSBW0FhysnNDL/5QVf0a74cElILf/ia94UMABzaQB/eBTZ6iwoeGF+8yHm5zWIbzG6ZkhiYvTD2GZgU1Lui2khxxYhMFWzAXHKiSjy1xExaCOKr+bDORatkDFDsKN3ferRCWPhGF/+DJn2Feniq2AUzcyDKcry+01jP1l9a37lNS+fS7AytcutnacoDMFz+Oe+CNr+N5ALLZvuz6fFd7Y0mcofW9DPXnlfNgLprAl0fZtE6fusb2q++YwIv8QZ1/6uHifKol5kkDg81+KT/LxAkpDxoeANy6/Wm0w2i1WgbpD/goL+BqcqPHSexZwsxuS6dqGejg/zYKORNQz3mny7EkWMBYGmmgggIvbypg+cLgDSD00InF36KGc05u/oweNbR6h3S0nK75au8KNjUkvuD1fCJy1488WYdKqkCzKWXRwkQ3eqS+Liyd7xTrI9JE218GXgxjoyDLzrAOJGHPsZ4JruloCWkFA5u58KqxMXqPs4iDgoCJcmZL2v6cYRvi13P5SQeJpnTBvWgtQBk7rR76uZnx6+9fV97JTb88g66h/Tq8fFYsP2WabUknWDQ3+cniwR8utpu/U//Hkrfk9olEXxdMe24duiGd0dVU7p9gK75NCzUyMJusnkrZbU2fa99U4QsAY0UA76Gm0ZD5vuqmDM7bRkDNczfe9PCkPhhxV0VNmUxiyQwRHCp3tr/R4Kn+8eUvR/mjeTep17a22OrloSULkwVr2DXee7OIU+fW2NlAKeiqEV4k=
  template:
    metadata:
      name: proxmox-csi
      namespace: csi-proxmox
    type: Opaque
