---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCx44Xf1lmWdBw8HEESWuwnrrSxCBrIpVpo5eWIHqQNg4szCQEyRlOJK43JniHpd+kG7H/UF3c3rbDdSq8iMrbCd2ER77r/IvUDNsOyPMCYjsk/OreRTdsMVuaMZEOAU//D46JrFkOjZ6Hinp+CsETL0IOVRr7OcVoW86XkEZr7FZPBGQ+IadcpoW+clAKnKhk8G1FSf8g4Ijq0BjIwPn6IA+Fi504TlaGZFxCTTFzTOxdOLTeBtZL5xAjQTppxqUBHYO/opozeeAwuLOoE8PhRA6WsSH5gV8Txyetw6y7qIZo13y6AGfGjH1BNbOVBAzYm6f9gGP7mUIwRL9Kdxqes+09Ga7XbyPi4Sav27gIy0S6oaJpFYS72AytiR6gYjLFNk+ft9ZVC1Y9we1YySqDybp2g3/1M32Kc6zdzxqDCq2Qa+xsLRZHQHr6tv+UE2hzAzG1pRxpx9Ng38B+4i9QQ0Zuv7dU8LhBuI9/a6twCfnhpQWt7yiBdeUerR2Sew4GBLx65wAImif5namDH54cC21twoN0NsXQNxF4AnQnuBQmsJggCEqFM5EotSPa/8Ht3VKSYyv9zNyXrIhzW3pxCGtTYopTCjvTD+R/c4ng+Y3Ky0XI18HYT8VaomaBYuhd8+1x4v4oxppEz57ERBTpeSEZusItjba6zDcT7bw8GGeOdy2i2e69OQiLwH7VgnptA0IybW5Z6lg==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBWa32xm6Bv8DDTKDEqXgsudYb/sNdicXiuAKqLNdFWVud6Y3tDAZ5N32d7/h8wnOiGyro2zh8Y8ScEgNb6gOdYhuMgmz42Kd+jEvJot9jfhTnl6n/Z8qpZIYg9UX/76qccc/DhiNIQ+exPRaeABjfR7M4IPqKK45K3SMwCmgY4lx13BkedQMCVx3tJ/CVpfIok30Prh7kQVJrr+7q5j74D3UsXw7PrtHy2d9TtJpNyFKtA1WX+MYVqfXz/+9FPp4Hl/oKDQQznqgInC8ExmygaYJw0l3uH7NVrxeA0Kfnp5qcw/+zWRfY2J8TUPQHg4zzSDzHRahdLexz2NfjruAoFk0cWOgVUXXeVwjEAstDQn0sZ1qJrVzJDt4v5XfZeXTeqmbt8ADWa351G6Re1yy+Q6BXwUGVOK6KJ1I1hl/MTKSIIb7rtD80EQC6yRpdel+wHUtIKMWa6iyT0i+QJbkVqxKx2kIi4iiZBE08qcTKUypzdaT8YHSNGDtDDoYfOv9zGmDiLSK4owFUuFOkWfG46e1fMMp8CwVute2w2qcx0RrSOGVBlsmzMmcArG7BOXmx6ccItio26gIBsRzUk4xVcIAUtIGAJtCNn8TcYl+8Jg79LyBSeR+LF04baeHs3psRdmz4oyisCK9vGgW8zExTVEfO/mIDz/+F2yH7K7Y7+5zkXe4TrEwSQxq6xyt8YCMipj9/jezpwrIU=
    AWS_ENDPOINTS: AgAoxp95xrsQC9HicdjUeGejIcwWg3pGgksJrglIPt3YTYlEgr/gWwpGmf30UKtfsrAR32Kr0SapLG2tCj8PVZdjq4tFToDmQbszrqMZ429/lOoUp///7NOj6/5IkX5RZyRBCWxlRSgjt5rEbjGx7ZeuhmSuH6k+XNH+Ko0AtFc+s9/NoKVR9GB07vdhXf8ekgly4zQI1OfK3Os1YLWTfdvqkrbQtvtdUTF3XpC0+rKEsfN/JWzVJUnt+TI6FhWG+nAU2OULzYxAigQbKfs39qJ55E3d7dw7qeIBtC+Yzj6b7Lsxa6l+SU42zgiLVktMcpxiSRMfWG9VBg+7xfZqUMphylA8FKNP7FcLIo0DqP35T9JwcGato4y5iY9mmxxTPkqATkJchcnyqiiusm549HOr6xYqVJ2vaj1K7MFRod5H0BPyr8CcCIwwfjFwWRFPRk1gKDU+flX/N+mA+YJI7vqR3wz13gNwkfIJlDBqE/dD97Ga0UnTibYf/EuuIBs4gCbnYpm8eS0rGJuBsiMmIZty6/fQgjDmEJFBjS4qZDs3tRiVseBlBgjFjV1fJddl08eu3SxJhyw1PH0QzYFOFJPEUUTQEwm92ruCmtXjks4zoVfiv09/2ypBOX4RBYGywz0yQtpqFuGMxo2kOzf/8+ks+2Jpkyj+ijo8JkWS7NJRtAhEiDddr5gqmdIpy85j8IqEAvMgvUJLCUvDVKZ1M/jomcW7PPCSQNcPiA==
    AWS_SECRET_ACCESS_KEY: AgAg5XyfRofJj/SDIKUH3FsMa7F++NUD97/S2RzXZJUYlXsHne3dxkgzpnHnNaH5VExjj4NUJwPLZ2vOXl7ttL7ICAnTAwnhgOGN+edElzTujKczFZ4USDdrx1spqUZxDVLDMj8U6/dZgZoaRHfqV3BQI+HlsU9d1Qm8I63J4W7QJB+5m46oxASHTT9q2qxtTcNRNMmrnmPq2nVizuu8DVRnDT/PkKk3knTbf7xKtO7dNvu+5lRV/KktGngR55yTEO4/qtkwI8xTTOtQSj9Rb8dY2vfgWMAto8Xe7mw7r1IAxwY8Leqqm9T24ZJ/1i71DEcd6dLlIKIkbGzPWwMbMksKKZuljKF7F3QBRXMmEotUqmibYnlifll985HgboH84CgRJL+8NjAMLTpQLesEl/px74V2b7M3F80ulKTX/fziskCgqg5yBDZ7dyjD8Ww3P7i3YyCkw7TZzEViOvVTv92TEloHZiN9SS84nhHo2bthSF6oxhbeNqNwhFLpZdOQzz01KhGt6xKTh5875K+/+PT5/RnGslGq7hz/kyVAvAUpc2Pvgabtkxz3kQjk7t5lN52TOugv89iuNzq4CBgQ9wIxlhQOUot16bPs13dZixnAbmHnITlyV6gyQP5r0lsnMhXv6yk8FzakUnx35afglcQzloy+YnGDY4xB5yA94dBbYiYucAkj1BTvyxTHR18ixEC9RcXRzCMVXqw3xQBfeWwgKbPuXesv6TW6pdGq/5YAtAuvRjV/etBI
  template:
    metadata:
      name: minio
      namespace: longhorn-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAG5xEFe96+1Ssp87pspIIMKWy2kqxX3KWlX7hZfAcCrbsdfS2vF9sWybiqqhR0twJ+n3y10p+M5APEOFP6SfXa/BX0fvJtycD0TDsjETYx4jbQIwo2mqYBXeYM/AT2wfEE6ft7n2F4npJ/YDua2sTYhfBAsnBwUg8Mytwfs/JN7OItMOPo4fkU5gurija3RvzA67lp+/mUKHyLiogzOlji75ERLFNOXhyJ7nn7MQf3/UZjI4AZucLR5AvRyo8tR3u4nku4SudgWV4agxyNPbl9LYlDlwxLZAAGuGTr5bzQziO2AW/1nATcY+TDSLbaUA4y/3qnVLzHRzrUXWC0ceTJuQGYqAJh70/5eHEzpIeFeXjog6vswVlAgbRqV8M4KSB/S89J7Q4fIA0ECTl0awYpCMG/v6kuCY3HMs9v2xsb1ypU8Jhbq/cc31pjgd6v3Y9JyrZEvKNxmFExJlK71jvAsSiFZW3V7dxIbr3C9PtyTKsruCR7fm0ObpKTmg0Iz0gNSlyoCCRGsOcQXhQpATrnZ1r/hEkPkwZfSzENdAKfXq6U2X9SAjkMICGBzL4w1aGC4GgjKr3AHsOZHdtEFn/F0wFGgv3iB7xrwRLIzYvFB6zH8qm3mAVqZCgoXtt9fz/mO8SAEm5YMgd1wUcUJcggiP7R7F++g4bUt8BbcGW91utKoYSXNBGOkMcTwVPeubntHD+2c4Ak/T9/DMRBPLKAcA==
    client_secret: AgCQQlPbIfK0B3svZin4gLKsIeau+C/Bjddh7ZqWLlD5zb8SwJVMgNu5dFJ64wp2z9rr3shiQYf8n1jLyL7SOyXPh+kbNdsOIqPZKEpuhYHq1YntOpOfTlNsRuvzYBpqHR2rnsr5oeVb8HZ0ybYEnsA5fQQDTkrjfUKx4ewqdX4sUiS6tAL7A7tKcWQqOrfyIiMrkRzpC782MyvRNV7Iet0Ek/uxhSsdxmXuAkOfL9BqRESxs6nRhW9uN5V6216W6TBJ+xW9RT8HD8nVHSMZtH93dznrj81u6mJMzCiefHXYSoab40UPt4HDsNDOLPtl/Lfr5dSnXp8D5Y+s3k6GSAuC6I9El5HLXFI74dzuUKFDtHNvouRRXyYeCAbLygSpX7fSGr3enAuv8y7w5UHZ3zt1OAhKFbQIL4mCm9Emwl9yFSCdCuIB2HIhV6lOtseYlmfCm6CtAkCWkwBCV+acug2igCXgZw/XI9aAiWhQa1PZn/OIVJvEK4qkyOTPEuLt8wBVsullQKabCNJyWrXA2ka78+TqM0yHU01sniXSvSFUh7S3Id9yI14+r0QYlqLXX7uu5zkAkZNUeMdk00/5aPhjleDYhrNv+g1iNdQdTz3wbrXlUm82r5/rjtTVp60CX5qslP8DAVe6bXiqthDg5iolV4roHbJ1Ff09qeJYzxmpuEoC5L1mxbUeI4Ssb5ie0E5O4balwp02p941b9tj0s5gWjaEOZUtaOJ7hOrAFnvTgS3Gq+miGPtGo9c5lNk0j6YmpibS1OkGpe14FKGvDHU=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgBN7xoWWHrwjw6jHm3XFj6H7BpMsCZoymP2wxxBYr58lX5ANoq0ouipTxxSPTdBkPY+mMpIi1cGqdwEArvF71+XD2uj0L8AbhW0Vhhepx4BrfMJkG9hoxVxjnW6aRMlvTr9GM4LpwqquGYPhg8ZUwNhJn+DaUw3bj2X/JOWsw6PXsrWbI3EY6xRoS5aLh3iXulsb9+hUmAiVgp68wDo/HjS6PSqQZP/b6mh3brtI8PuKxKwy6n6c07//x7MjZ/rTr7h/QM1stmkoEgV0/8sOl2cjC+shgZSK9uhDbWJp06uD4eS9pSLacespKpGz1kRTE34/GVYVtFfpKZRSKmdfDs5oJUyP0St25KK16StYyEJhY6G1ie/N2LdvDiTmpC0JkwcjZGHLiEaE6Kna922l8CDdcytepDk+jej8ZP0cwJ6Ir/QCozWSxKhSFeb2M6W/jPerkkhI3wvSkUdDdW2swwPmZrdERO6ZOW5LDrG1ji4YwbJKeCCNIOFO/Bs87twsXAfrdNVtXjrGK7zsMiLiQF5Z28qk9k3ll3PjqmCfpSi4Qau9NFHG9agzowsWEGQyG+WErCY95yjoNbpEcQsHXd612nu0uF96NcdDFbL8yhZIV4nnIvVrpfrkJB7RXX04mSr5iYOEryiXdOrRqj4LOjjksZEf83tTyO/rh0DUfIdayGyA8x3QoDYTStiS7gcl+3LPKyoG9BhTDejNwUQRDRo0m6obP4Ii70jjyUrgWyfraRx88zgVuet1cxmFw==
  template:
    metadata:
      name: delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: work-delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgBFw2d5fvLypjD73it4kEpy6AiPpmF0QpZTqu+cyHYPTU6Sqs8mwq2tvcDqGdsUNS21uBzcw7bz7KfPkiR3RlNYZ0Lyjm5xDpySOk+VFDzL0z4K7PEVCJIFk1t8QeEchRMmf/pX6TsyBixO22e8YxuN1UeDgM9gpi5rBV+HlzhyupcGHlts1sDkjbRTLDCEBPaMRZvH7bUd1RoTgKbXLreSelc5QAsPlKBociWbM+V4jsWF4dBo1WQjQxiKdfEBnD7FR8aKORla04DSA4CrWrBYK+WZEUrereumdx+Ow4/h/OrhhAsQ4j1QkFlva76IGk1VO+XlH8gjKA7XoRcSQ5N/uerNTMev37nvVmmam6EKD8c2CtkGUQ/JVkxMT4yYHSKSWQXqL03Ah77ns8rvb0wC9ANt8hbxdrAduz55zotLRTLR4gAj5oiicKcAnwX4xgc73bkF5rU56B87SYlfftK/hobumod3aSd1GRzMRdoCVypaGAY3CRzVT0V14pr26V7cI2U69vOxQl+x+t3inGEoZj2I6O3mk8SgGyTINawidWY6orGkl/CA9JIp9KHnsC2cwRUzmi/q8F9/FyDAbiJCy6hc91ZoT1OMryk/gZ8pv6CLU4X9aVwdEkOZFqhh2b2n24oO59eXM7vF1aFcElS/cEzIa7CgepqNHEQ5stRbtyzP+gQOplMZZSKTHu5VYblf83tcxb5n3TzgciPzfR21jY5UpRbe4yzJbtwCWrNnic3QXN7vjXMC40gpEw==
  template:
    metadata:
      name: work-delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
spec:
  encryptedData:
    pgpassword: AgCI0VyNOTonmGrhODB6OqJJsaO+Ah7jbtkAqt1AIvETErMiqZkYqO8PmbwBH9JhuoGZlasSbil+oN43Kw3dVwaptdaiel+eZ/u+eW3CAL4lXrnYwnwGLWkZ8zBHrpPNvgGW6382izvBGQegKsWZPtojkzHUOmNRkdTnmDlsPbsjOCuYF0x6Oj4jFsnE+7kST6FwWt1NhobKOYCBDBxNblxKTxJZjMK8QBsPOsVS7/3uoY4V3Q7e9XonkBmP0NddHtd9QkiM70j9EqgVLxnLuiEA+1qvM3845tkx8eETZKzEbV5uar8wXm57LTTGoWfoJJ1qpSYBbzBsxE9jjSxu+zOWnKI/N+rIJZUZUNiREmsf8UVDEz9A0h2cEMI2f9TQTEkhLoq4wCV1m9ucMRRWCfgNLbUNmuf/KOwSRi2MecWezhtLqL2NsS+ztp7wcgJikRm+FNqyjuLOJn0LuVL6v7bwMoazCj150YG3Av06AnBREFPwoAAOawQYCOCUAzCLmMFGm2kpXe8JCaDEMf4J89hKzr1REztHjllBWXC79mc3Lapb5qBwbb4L4buzdpAMa0aw4UJasJX+BhMONMMyyCJUPcXuoHJTdwAnV6PmWK2a/wvXC5lNy2Eys+MAcFQSTbjNSaq36hDUv4t4Roij9q/BYmzxyjCNt19Xa6pclS8gqqSI6NUj0S4JMQ3cAFIsQguH0kRj98HBnq8k6FSUH59CEHFDLrOJH+dwVKLP5xHHKtAy3hc+hkdm
    tautullipassword: AgC6k8vBmjVXUGBLc0ECCI0vy7styRo1T01NJ7kIjmoESD/rIx9Mm1GmiSLJCEDuVt96axWuBpJlCLTW03y+L7DUk62HyaMmBA15dZlw5GK5UTjyvClOMsLQkEtGkPvTFaySbADwsudGloeuK+w8cQBEZUFUnx0XOyxsg6v8Cmvb06MtHLYRW2UVQysnXZgCNWAkn1CBzadjYD6D4pZeWbTI5lNe17q/S3cys9bHx/4iro+T4pIcwD+/XOVw2w/1q/2o4ff9gQ1edVwTIDNSb+rLwYFPV5tpL+GIQP7lwF99+UVRdzTJ3+psJdl2C0JID/aFoeTa1NZB4DNozZb8qmOcrRPZJVIX3dZP31LkILzmbiO9jtvTR4USra/K0wXyBZoyPMO7f/a2nCHp7n7AlIg7bDj5nDhKFT6jJLiWUTPIjBK6A2ss4MAgD0Ij0xoR6fkRwpSrZ6WGanmkGJT7FGGzBvJE46fyF0jzLLWoM6N+PlMmAZVSIa2dKVNPkygzOjCF09WmBE2c3K0K9XPtZlpZS+zpVKKXc+zWiliJNHoYa0TdACCBLoO1C/RNZSO/hAjwpKSvRp7pk2OpoVTnv4H8vIEhywmiHn33aebGtiAgc6rTbKJBW1xiSghonnIDalOT3rcfA2xmop1YIgG38cFnE+1cmElYjxvrIlzmXzpEt48R9Z+QDSvrSjP3VcRKTNFa88H+szPjb9f20BGCMn7Ev7jzP74M91Gf5gZ//chztA==
  template:
    metadata:
      name: survivor-tracker
      namespace: survivor-tracker
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgBvLJdDFllF1clP4y0G/dBYJ2UksaMFZAMORK5gnb/bamZ2i23aYx8e+iO0zInW+FGjXoB+Oqgjqz2wL1KY3dGrIKphxSe/ABK4vZnlVw7kJMEjKvsDZufZQGgFtNHNWs8RDUZHifaqDgG5SYHMkqCFgjJx17CfYcVEFqUZkK5DPzqwWTWu2KFUy6RFB8RsL2+z+8AtxlVvwCBP2PySfXvstlZjLQ7O4+ZuoCFFh7RYwbhQ8fJvzcQsH3v9gaTg3KFpN9QMed0z/XILvYyqi1HGp80TwOSfV+skUYrXLSLz/dPhHU+rm6ZfdXUv/mMFM6155p5fH/J9jPCUwaLDhKZn9xZrUlZRt1MazplwAuTals5eXVAaRcOeP2lolL7cPVAA/0d8V3hBj1qSM1tGRXDjxGppsDROa6CoEfjNtcLuZOaOnfR1RWt4yH+0C60KT0Fw36xnxq2R+NPwdHQ749JYnJ+Ttg032t32O24LsOC1Cp2O3klCL7Dyy8Yd6Q47SW61Fvjynf2E4tS9lYFWo8YoqiqTd62viIW17pBmmKTEbdAedPfmP1SkcQatQ04Vtg6nmfI0G4g5f16vrcWX3x7dkOniXh61k5iWgPO7CaimtEivCgxzgyoitmj2idlwipyLeyvnsvkBvTOlKllJxhKJND45ksD96/oTZY9QgVdQzBDq6akrWlVDQZwrA/Yf0/ByW8QUJRkaagrUO8n8QPcVqLA4N28/UAQcDRC6hNaZrJO81P91lN+7SL3Vj7SLthNq0wrHajgMvRzAQNb5ZrVoT6Z2lX7gpuYqMTTtCfuThr9KRd4wlY4UUot5l/bOQFf7c3yjS1JyhJzexdWB1uK0aoP7OQb92S39On1LTwmgRDa5lwdqcej3ahJKMpj/DE6ZNmdbJ7J1pm9B1Nd4ShypxyUDZAxh49dydT6BXC0N4baMrw==
  template:
    metadata:
      name: proxmox-cloud-controller-manager
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgATvdMxZH2Egg9LHVhYywP+3CbLysiUks9yQl2C6PjBcA45gxGTDRwx93y3oyO4up2G24XfDEmjODh9mB7UybTY/sTqGZCpgQpJsdrD+VGrEj7pGLfAQMOImHlJW9FOB0+GeZhzFiMDaJYnJjxZQDt4D1FBcbI47Vh8cloN2Sq28RMdzhLd2ZnNUSvkexazUF9/gk0cxh02SFkKEUAtPp7Z53TUnEJiVm5IOTHK/qwJ1GiUt54vlt5xjxUN40XG+5e6UNuI2gUAR2zQXze5vyRZxW+fRlo1tOqulPFHlkowRtiaFGvtMlnKSqQaqqMAZOJxn6pi29u2JaSTE5S/N55OhxzAi1FT4q+FplSxr+w+24oztURuc5xNxRPLhmisBAqEjpEzefX5qfbcsY7yfactgOkCwDOG174wB5/W95DEfiVEMK5EhvHGMeJGUfb4k1C/T7fJWWpWY8DZcPIMEoeYHS4p4b0HsVJZKAkP1/GfbNY06Qhi1m+aX/eSc9RbMgedQXXvDoxtyLmzT6+/uVS8x7586E8tkMDw+xayshOo8jEpO535Z/c2lwzxaDwNWsZ/15/sipxEzyB13Q3kmlUoovw3JYOp8Q7X5DfbWGunwUbUUOx+7RAWpcjBKimOcCpzfbS3suNs7N8frule7thw6m09EXEyfxLf55APXd1z749iErE21Dlb+btth8/mtE3S1ggmDRTMcMSlYnpW/0CWzErbONN1Z6z/Y1BkwJvKQX4lNB0tl/PekgOTC8VOErzIPZ56AZVWA4cLJiKlw78V/CF9wPqB1/gca/pEGKM1TcblEZ7Qo+BgKQvlypDFAV0EetuijY68gOiIzjejVB4wRs294uDsyC0dfE8EFQHy0lHhk/0GSp3526GRIrdggP/AjM4jfoiXFiMDDTI3assQk57tVwnceKxwjtbT5xG4nrf295l/8rY=
  template:
    metadata:
      name: proxmox-csi
      namespace: csi-proxmox
    type: Opaque
