---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgC6XCppRgNzXK3+B8Mie+gvdNrJ/0mZTebpOZAyf8VopQWzpe9mAP1h4l0PwNj43qjqZp5nOAwJTL9C0gvpM1MitCe/fMkaEsZZdLfAgntTcu194b65ZtBRiXy89JADIL1MqbIrPk2s9TuJvCkn1vxa0dpEwO7CSUP/KIO2he6ZQM7fSJNAHI03dKViTEo/hYd1btxHXwtbbthY0fXpQD+EWA2ATKjo+ktb9MeQ4Htd0SITmPpCJ+MNnXwpweVgi25qnnAnlUF6fZrrRGlJpKQRuX0HQMm3K4riuLT9N486BJAh8jnDS3HyI0h2+qUTzFl0OQDzx4jl/BQoq6FbOUYxz1eMK4y9Zn/mCcB5ZAfg6/Db9d/hwFBrtW6UQPSnpxKzfl+fMQIRuEnuXMtZ7XstdiarWjQBGI4XtuQHQ4crRqsw6fPmrM14IVvuRvH/g27zvXX4wrr3EbInYoskaBiomPTpXX5OmQ+KisPXlTfH5+3mXzcGM8veKoDof7Tfrye8ezi89BkRImCnyVEFvs+2yeWAc1eUT6SCM7ZAqmPw0zET6+SkdKW/zZLsl6YyO+kst4fPEQgQfOTvyrbjuZqg150Pj6QiIZM5h4lScsZaMnFYFxRsSvr4Mu6zDBZRRCfSErJLhyeHFuvUclLlBMiSINum73ZvtKZTQAZE2uGOhk8nG5j7dJFQqCcjvBGPZ6nOGzFQaxmgFQ==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAHnJq2hQQlSQyvDbUhV5L1rEvNoJjFRo6//HgnKxIbTvRidHsSElkhQ1AveKd7J/dZm3zHj2Cm0fv6t7mx1ZcEGM4TqT7ZTgKTrkzyh2euBKjk2so9frwqzxLUbo1amWDkfz/BMo0h43DgzyJTaV3RG1zmNKhDjDrGRNvdxyZnO9J/pU2vV9L+v4onM3peieRX9A9ONXiuAPsBu9unm4nqqt/atDc75nnnU/wHyRWwrBEJH5W1502tzCqmnzZze4WwjrWKB8KgrW3qVhSyC5a57+h5j7TkR/4qa9jUD3XB1QIQKKfnZktg9mls7lb1OPbv+S63cw7I4a+MaCn/nnIvs3oO37rAOAOmhJOXTROjnj6Ddzb8E5BmBWYXkThf7dxCcmUU+9Vzb7B3BJOqM/X11EyCfIyLOUiA9G7W9kHyC37SImV45sYzn60yhIr/zcQT+O3Xq5fdMTmBy1bXY9DtSWHi3EnZUxLcr/6vljm7O42SaMs1puNX4rOB15s1y49+nEYot6Od8OgGRiThj5ynLxlMb0cGhZQG00kg1txAtQYI6TKNn/B0p+GfyUsO4eau5Hf3uCIoArETmtGAoGwlytpF2jU/yqCenQdGfyaTse6JSdEcNkOdJa5lJYGEfsWEqufV+vRn5QS5CeGkRYWueYP5T1ogr3LVaNmoK9UEPavJXq9O85y8xdwVRhTzQHtFoFlBIw+JGDPm9huRU2mJZg==
    client_secret: AgC4HVzYe6abt8C0ttWupuAHcORlFVcjeP6bYAuaIRreLEcwyljM7SbzVxuxsa4+en4ECFpFhkDH7F1Ta5iLJapO3q+yGbFfFLLn+cqi1rV+0SQPAS/GYNRaouTxOsVpqyHmQXAmj7b0yTnFDiQW5VLAhCFgTQFzgdu37oxC2vMBcub3BN3/S2k9AELa5pSC+V00NZeCjYdc+hcpdrEl19uX1pwyN/HWHpY/hM5cz2TzlSJD3/LUCVpr+8idg60pgtmcBcdtdCvOt6fCn44fGkxLdFGJU85Ijme6NyNKfHiOmzvPGGUHZDUbH6nT1smNVh/+LjqQkHPIGqqZ/qaUXWLGIo9rYKsBxR9RiuhZikypYX6iJz5fkzCQWvtCPLUyHaiUGbsYk7WN4pkC5WviYP2SuwVlIBa9nlG8tioJH3o3ZNhlaOebGQ9IEUOOHRU20uGRm0nvlDIG8eXYYjkobeB+7wWj28JJL2dfdl1Q3EJuqJ5ulVOXfEyevJYw4NizuCJ4j7nwfGrTrl4/fn/h1v9WkFzhrxUUX5OEz4HJ6zrYOayN7e8ADvpFGJDECvvCk/u31BVwCl2C+VAXnzdPtsxCftcRZhnIFt/ay/0PkTWbR1IflxZwMHI7+VSgFzArJmyZzOM7tG7lUddOcbOyqzAsRwI4miWqYS1bVcHL5dWg6Hh18cmU3CKH3eM3VqXHZlK056MeQseMNJ033Gb0FA21fCT2O+canDx0XfHL7wlJoaJOEJZDdKN+5303rc9W9FVvyrOyEKqMROKGJyAVEQ8=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgCh2wJ3HW8hGVM7Vj0UgssLj0it5bX13n5grHO1y3gCd9nh+nxAx7h1BDhQUgXWn5pTILPiB1RWNxiNQIczNuSapd/03uxhrccEdcVRc2yrgKl46QQOgs2wmTSu/1d7qN8PkRyHx+hdeB/xLhezskxh5jblXRY/eM22Vs4Vw7PvNZK6aMAle86WazZE5gueHmR/o6bAIMAr9iXvCAeC2AdL4CDnMK5OLC1iJ64URFzKcxR+Ar+s09bL66MQpsUoBJxyRzr/56aVq930ogEJcSIfzucYm7SB8JZejDYj74HroXLM69j8l5fIVnXdH59RUegfHz8E+vWzCSN2FAowoePLlDJ79UmWNIUy9NRuEO9cg9dMK+WKw0a3E4NaiQujpXrUlbNbBXwTAsAa5rtpN53W0Wfce5LLuQeul20rGA/VkdRTQ1AuZznLhEY1Qh2emqJvfdYyOalIoK5yH1zbw9sQp4M5Gc3xlOLNbFLdTOka7jjdGcD7m0NQzLEOGrFFaWIZ3bCEki9/DHtgD8+sqz4gBC/s0ZfQUV+Oy7aV3J64keHGyWUgRcUr5vtyaLS3obg5h/0gMOo8dSogKRBSIaH6J5besHi5nA/htIHje+KCoop6TIZiOKzc+BAjGK5qsUWjT9rTOwOzjEXRdgrfx8vMzAtikxxQT1ZBNmXFWcqIQaQBV7vB8Awe9mJZdTV4SpeCl8Mp6FNWDXt6meOh3ZMQ0CTmJLJrrCzAFOG8IrL9PXwRHbzRh6Zb+S1zjw==
  template:
    metadata:
      name: delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: work-delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgAb9ccP9jNBr4PsBkIamTf5vx6xE1LF1IoCOYIbQKV2vSaM4SNLx99B2OPqr8PQi6gcsHPf/jYuypg+S+TXnZG9argBNGkEVhH5x/Ug8QF/CJN9R3aFapsRvKuBTP1BxlQxI3fVqQQic3dveTI/i+AE2WRtpnzoPTsaVWvJtr0QHiu8GJPcKv+nzvU7d6sJFsFJeLkX3WqEjFNci4tuSoV8k9DPO0zur2tm3bsU1PJBSSi9gK8lmt1V/XctGMdAl0OsayNeOMYK7Y3gZbavr2BBKFtL3LJa5Hx6xTYcEUC75P7tuMdjwsAPVwJUk71moFhQpXTEMSwUZmXIisapvleNMHAC4InsNdApTxwaGpW/xpJyHxSK2Ooh5y7T5ntu8KySTBMy2RZCkFPcplK7DY5Tyc7rHFx3cm9Ljtdk5VY55fMHdxH2xIgeXfJFYid/TcfZ59RuCEFB4QMkPgerj9DzmQdnAgZ07HDxhlhXqJTtgX1U4DrSZhFAGI+cfHO4getGoBsESeizoLrT4i9I4xDpaZF+mjv5ofpUGg9zHH8yqmRkpCoLU+8J8ArtOuSr9c85bORxyWKw1RN6OPowf0Jb+xxvygBxTSFWQGRrzjc4jCeB92VJMxbQGbv6chk14eJKJDH9/mPZAQ6FrE4E9SwicTgpnPGwSGrgOzzXzLI50OsM4x87Q/Lg+cm9BoIBPAa5Moq7PdTPBNxbeY0zfmSooCajaNskoS0P1RAxtzsIP9qhs6Hi/P2JGOE12A==
  template:
    metadata:
      name: work-delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
spec:
  encryptedData:
    pgpassword: AgAyBxp7O/5Ot+4H/pvr2vz0ZFOq5mPjjD5XFgQ3q4vJhG1uN2Z/dsJPOjaonu9PZhn8xo0CerTYIqZQqmejelcfP2lfq9e2s5CV3cU0zAdCFxML/Ab4KuM44aByLA8YS56jzYVGNoKqldYE3nA4mccOFerq/NZg3QAFZdWx/sQWz6WUjIH9cl5qUDTvphCsCVsBB7/vbmmRLc2yjW70AnbIt1+TXLmOPJlpeXvrtED+R2zGTOPeK+btPzH0/APkMGWG58RD2D/es9NC95a7HbuoBgeK1Km7J60a48S+2+vnZ/q5UNBzbR+S3wDxGibpfsloazYaUWzZGJUjHbrw5ip0SWTp5CJBwG7OhJ0hegw7xTDp15cBveXBupKW7r8OA/KiMfIHvmg/n7HOhFg8VtQOFsWAEKhQm2tDHYzEE1F4uFUiYhHO1SXis5VVhvruEAHowicZkjDKIktb/qENXu0Jhs3EhdkCByjB4dA8XTJZAYjtL7EVFOhI7FyqjCtHoBZbA9fatWCZwz6ydIpwyXEyvOeK83LAvHkRdEBbsVH7+RfdiU1T6DoWu3NhPpLaWKHq1SOXd5RajsHyP0P3vKuLHP5WmRFx1EXkG2Ao4DWJi7HpPWKrLAPz5EP7rvk89vWJdBYzG903zYznJ4UdpaPa7ouDlkPUAUbbBWphb40cX5goPfF2s6NCidyq08aq8pLLessEN000r7dDv6aEJYoASs434UGPAUVPppnhnDO3+oxq1NtGHGW1
    tautullipassword: AgBtp42KCsFTbSg4cB8bm8CtY+AcloEaKRJ5ytEVs0eQXw4jichhjehz4KjRvXqt29cilwoSy35qojIOcLgp8sKMI9CYFUhbHvl5QVJyDH6l5BhPQ6rYMutkRwZfpDoPq6281R47Pt23n46ZCVdJrtvpsapCuZ5EhpNXIK2mBEqzixquPCcoZatwxmS6bI8t9U8B7v8gsPIbZ/r+cI2STYELtGpFoIcyVOhlRUYi0DTZKv9x0CWwMz5mVsL+jNqzFFX9ODwNmiC+W+vTMuRJ42XKBZtnmsyz4dp3J2y4h5bZlrRpraVRV0UIEdg6FeRJvtu0Nnr2iInCj3I8fpS1xF0zyfFdGTM5l9VRvukQUIodkDOmjGRzoW/r0r6pjr5pfGh0XxLM6ZMYIjtk5ZI2Q9NUMAN5TtRCVuA79zloxRlaS50z49160bHVg7D/+o1rTxo9USCxZK3XGSY6LVQcMLxdE316lrli64smAvzz2V33ErSeb5v7/WQZojNsDONLQmAilANqGCLhlWdDs11Work2aIA75QG/6VJaDQoPEJTMWEfrT268yteGomJvbb2exWkuNE81MVEDAQ23WY4EZuhUO5jW2CoFGE5YM9So21YnQ5/1Z+T4toqe7azcZmygQypSn6cguiv0g8nzr79607IrAYiEErMusU0KKtTH32F46vZHHkOl2hMHBZhMG+OEwePpl2zplH1pJhem9de318j2mHTWEbFcrgNYDYoaW5KZ8Q==
  template:
    metadata:
      name: survivor-tracker
      namespace: survivor-tracker
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgATct69IXhGKE0JqaJBYopppmOo37n5nljOPCEa3ynH1kxyFPYfCS4bqTVBMqOSXkiEUDq8IQ2yIAouk8xrNYQj5wNUr3enwrR9S1X6dWhS0hJ/0AzE2IZbC9hr4/wmLxzhiiTFnVREa0BJXSBwQKdNdlDTicIP6/HDMtwSHHDMXsZJPV1dHxTA+yvKmUSW4iNg1lGSUvyPKb5w+iar5t1N05DkIoDMJnWAAsPuSAFN0O/edNTLbVxhKWSlOBD4ZlGgFwxak9OGHFcsa/su1+2CWpdzrdTCVDH4x6gRIaxKu3RDehY7QBLBXGMdC+XY/dPGtDmDMqNte9vqN3zl/WDT7hwCMpS2gE5nWy9g+41S5nRBVex9XuCfH8I3BStRiiAfFPb3Ud8nAm8YiGOpJWXq8P0gKvIKnde5oUP/TFvoImbmiy9HWQq946Wz8fiO5c20VFdnCbZGwCbVJgjRO6I9TF+P/ClS9Qn+f46vJjpPnqyt55tOlCUExbAWBUSgXRRXBtogYOBXjDPBEYomua658hip0TBoH2pYdPlqRVP4CvY4BeBsE3djCaLZwqoafZOf6UyOySGFwLCBtXVlzeUskXtHsj7DwkMsNmmj+JNmEQ9S7R++1M1DZ7otY2bR8fQnnQVXkLhFF2xiL120mpOY0/V5DwpN/293QTKOImcK9f/wJ2kMPwcjwokSgLnVc9jExY4au2A1iyJlRtO9/rcqPYEoEUlI6DDmmz0/fxjPkSOPNrd8F7DdiDADmZTB2j6RnjwrA41P4AzJOeq4/O9xthkXnGAAP6KHq2ZVb4AuP/uOyyxbNH0IxMcAq4+kvCBd6POe7EvKfv49aeNIFzESv+nQZRMmuQJpY1es3cisOfkv3dF671iemTNNTB5q8iHx1gDHS341z7Xdg8kp/5QraOvZTGZ8brKSG2jEl2wtvAWd3g==
  template:
    metadata:
      name: proxmox-cloud-controller-manager
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgDYDNzTWd2GpivtBUmJVbexAJ6xDh94ctLWOOY5iVh4LmhAV0Skj7lx12bt+SZVIPKqfAs5qdKrT30kCcGm7BEB+JtSQXKNX8XPLqU09OMSX1S5gbdoS/vAMs4XD5MXAehsvUwkpd7dfOiNFsOHlV2azN9goK9dmHiTdohCmUhfx0K0BEBCP0qtbBSFSss5nvuqvOq+TKzGPXJ9iT/kK7I+lPos96YBBMlwRxqgQF9haUWUrJZbc2ECA7d3zrtO+v90yYR6UoUm0RmKBQXopTol01rGGCy8xq53M1MgG/zXYVmfOTBGfoz8rEJek87qQc6KPtVuyBEdfBYvsPNrfn2P/xJ3ECV+xgyNakEmSMnE7ZItNJtNS/aIN8wLlEuQUGX6zCgSXF0eSA83/sJa1mvRyqToll54mI0qEOR2Or/4R3KweDKy1EOXtvVPQVbKwfAmHpfMpYmvfELsw9NR+Lk66BziLhlXLE+imn6Zb1d6W3fNPImJTfuEySS4LsdiIQfzUQ4K37urh+au2O7whbg7tD+oDdRfR52NFYl82gdGQ9h68Yx0KYjla0f1xCJ6H5bsDgFLf5vdpBN4igE0afkM8PnPgTGiXQcFcNT/S8N5LTzC5MEqD2IbryIXDzGb7MYAxCbyA6lJNAhNFEDPcfzy9/aA9uDRirPYGrzGlLlmeFwX1VXSfF09cGmWKRKwxCz+8LlVUOpj2prICw+nhKxZQZOvcwjGNXh+cRQbUziE9cW2UbwHdouQXPT9ilj5vojTdcCLXAF4C3rfaXOBZcRfxLzDqjA2S0VjdE7TgYkf6/ybs9CfrozMC2UUesNR7QJfEOgDuOk/hx/+NbnamyZfK24PbiwCwI+CpumWTvix2x0XgKm48AjmpJ56aHTs9FGEALCQcADjvcexiRJtGniu3fUxLYp1CAckU4SfGWEMJSDGC+T7Dhg=
  template:
    metadata:
      name: proxmox-csi
      namespace: csi-proxmox
    type: Opaque
