---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgBiEM3N9hAMGdI7XGMUEqK5SZkF4KG+QbqapkQxCDL5cxOtF+Lwgf2aq1IU53DOVTZJya8ULoROVcYCTanTSWB+oRd5GXS/OpY5W3yexYjTnU3LAG6aBHdvNRtei8UnxhqmOxMcUsadha+9uC5hZdr/zMbclUIvF4IQ2LNo/JqMsoIBnBWwRKPbnU38LQaihGjfk/6Oz3d2XNFstTwMTbBcR4VUR+LUp6OplGJbu5aZzt7f9WYyZuhqKOXdEKB0CN/22sZHY8rdCCdfxEdaoIDuYBGkVQ9nC49MU0le6Jc/wiWtp8Ca28n+gQKUnAXXWMf2GnAPa/kFTE88g+tLQfsHy4HcOiuHYF1OWDr66kvW0PAYX4vLMs6WrLYGgdZVFfA5xpNZMESLQ0N3HkoSfwDQG/JLlBzg93OeVD69ZYyMAAABB1YLhbIgTchWxS9TOG4/uER+mQKEAQkh/HUid2vcidvUSPxk8k1SM4WeELFuTyedMu+CqmFUishmhunbybJ29X1xdry8rDDuo2iOqhXV5MSnlWVC/UVwfRUOtakwBlm2CuPhGkoXYzqHVZTgFCA4LLySUnzSt0qrY/F8mc0wNNNEJc1Jod7qxijis6rKVn9P8vV6mu2P37e/5zXP2/an5kGjubY/j/9hiGr3V7y0e5Ato1F2X/bZM0kMX+OdsKjxDR1DS3IhCxtn+QQ0iOqzaQBb9y/hDQ==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBL3Fiw9/Ptiw7kGAhl4fvyVSuQVXWDaL4IylqDWh2Kcd1jECrZpj2DsLYP9RhV9ncXsE/IX9pHuvfP8jv8LOJKL01AMuWTnnoTsu3ZYOWAAOUCk+jvRpszNqzsC+UTg+CNsTmoP9cBXuTHK87Mra1tW8uJzDWPbgPRjaCkitllrMvGcia1jD2Ugcxdvh1PBkPLXbjEWIzh7bfNzN0+ByrT95OHSkyBmqa8EzprJJKHAHGhgCFSCQ3V67LwYNNwn6rDhvs7wZQLOswOJnmkuhhad9XelBd7DuiPj+MRMa5yoIUW2V8O//tbnmR2+sezpxUV7GV7PpVVxlVL7A1Xr7VtLWIjIUmDgRR7M1oiU/R38CMWrmm3npDEjvyrQOKIg53u/Ii/2QsnZN7Q8QzuADxo3nOLfvL1CsM6JUfBo6dwzxvTu1ZTfORFlQGX3z3Upz54ihUZnc1urRgoKXRwmiu3VebJ4kfVtvC+jXGcmnbdCfmE64c4XHBkW4aXFSBccHtnfnrFCYIZp4X1LP0sWIiSGMWLH+5f/fgNUOv5irK+BU21TGFnpbLuciQpCRZfExpvWOUur0VjKTrj2YiQLY91uZ5/T5yFZT48em3h1dbpO8AcY2QUuGC4o/34zHg+RxCm7QIrhR4KOEvnCoD1LqVb0clVhZYQHmedBmDjAXLpiIEplNosXA5y1u8a+l4Or2h0MdVCv9ykQjb+VXNs7NJ+DA==
    client_secret: AgAfid4a+jOZb9DEZAxxV9OKPNtz4Onv7USWX9Ebg2ZSGtClGEdbRHroBzjew2aVQlOOoaHYO7zrnkRv009F2IF91JqDIiz5p102LQwP7c+OV3QIaKWsjKI1byLewZi3kOVFSIff8I4vCKdmCISXP1gfieD/4tFcBtucHI3U2NinDzukU0FQg3cGr96D3Yk7po+537tfFlFW0YLQ7VYZVAVhX4Ml7a/1rqHcpONE+9Y6rv5Mf0AELYoGZzz8DRnB3iYnCN3MJCnYdmSXrOrFes6snnvYP8+Li+/OMwx7v9GPXgKZY1VUR6BSK8Zsp74w1gXbGP4v9OuOd2WodsjqaMRcC2z6piS9penQQC2OPPoBAx7FXx9FXB0EJdlgjLiCv7y/yk24DbLlEx2YIKNyio+k2KhACKgUDHtl3l6bRvakdRl5faG15WiehNtxEtRixPS0oQx7xhXq3d+jS0eNeO7deQE9qeD4Mt9OKGgusnHhnhZs1XI38UU0PfFIMSscORVP5Xz8LtAgGHTcEcfc1tEUGk6jOj/vAef9gUJraLyrQasMfOnaUr0L+fAQUB2Bf8y66H4+4Mq5ypz+2MIM+OstUzNusJ2bbIqPqJ7r+QnCdZxkMyvuGWv3pd62pAfd+rLCo6ePBN27A5VUftbwCkRFBOpFfBhLP5FVEjcmYabgVB1wIxwRjigFq2qWOSNAaJypXLex9FU9CUDKi/BMw2VidUhPNKRin9X2QQe2pPctBVp/BZ7YHQ0ALCxR+0HhpQYrHNdBAlRkfbzrhSyJfTY=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgA9wlW76gA7q0nyLQiJO6ItG6wsfKnGtibxOS1zoXt/sB9DNgx0x+nsB5EimsTrvwHaHo2Dz1jQRuekJqVt9lEm2kFh39Xjptbi4Lbqbfdj04V0UATYQwuUHTE7Bk9gAk0Hm1V5hXd0zCsAUry2gc91q3m4cHy8GTJimavCARGfiR6IM9Tnn+g+fPnPQS+mX/Z52xec3bAJmHi5pfhMRCKlReNydyHatvS1rzcwVUQb01veha2W208qLS0TDZ4yorsve8Zo4WjXmBS9O1QH9604f7/wUrg9GTOFFVPHmm349jjlgGDNQhyIYVBxaX4KE8aMkq0wUakEsR0bCiJC2esCNJsCtmgGZ4g4R0Lpd8tuQOGy0YcKWNU2zVo+86pBS0MkQ9PsuyjJww7jcQDd6BrnIAv01W2P5keCcNG1Mhq7vUt3zF93f3i+SV5LiKQo9f4VdYFonBoa4EtPY7AqEIqhFKT5VXFlAKceDuLMW1zrEE68Zpj6ZCA8IVsWLTvVTL9qnSKAVVANQhlGNEb0jQvN2oJ7IDEdBABTeBizEtJPLkBNZ7LDpZKIDpQzPB7KsS6Dnip5SZtn5xSyjdE7BoorS+VkMVqN5KZw8I2jE4Wf3nRn0lDmLF3THSDf78cteKudiI/fsZCNIHWraMq0lWxbbVrzM+oVi6/srfjH7T9nI+DNwkPeqhX8vqHuyko1marbdDLA7z2GvvbWZR3m/ms4mGojV2s1LryFcBLUxMwtMnL86QSTbb1XTdGxmA==
  template:
    metadata:
      name: delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: work-delegate-token
  namespace: harness-delegate-ng
spec:
  encryptedData:
    DELEGATE_TOKEN: AgCWgtPJi0eqYUi0MxIJMHLTvqzVrOBcF5LUUYTH7gNactSlp+pVg9UPvEkGn+2/VuLHUTg5Fixkc9rFyrqCRnYdduSy5qyudr3qsJlamis2WosQE2dyS++c+vGfA2IbNDxJeUn5XPlGK1Z00D1ecmrTbRAyS9qPyr4Nlqljr6RGBapz39RSonqHhFgq4EGw5sXpYL2itmlt9kIOHamYM803pYKPz2nnWkcBv8ku98p5OhFtSbFJZhgW3oW7nh9ps+iiQpTHfT0gDbRWawnFd1tD/gZDUwxswyUb47VCxwueXtQ7rrT8UIRdN25dlxuseahTZ4K/VXiJ4thYwmBktc85towJ9SEYt3itN5/pnF1YNWEVcoX3izyDHqTgHqV4tWZy3rChXsBJR409/WI48Dgxoe8OxNZ0NQyCKVXbdXqYW/fErrrOW/ggIG2QKin5JpV8R1/lWRV4tcDx//R8O3z+lF1S2NCYR9FSUNooreapREuKb88eba6NsM2g1X9pIpqYpV/4VZV5qs6lzzAHdr/DAS6+tsW9V/2zjK6iirN7U1iBBJusaCVmPQj0Hv1j31ANs0o/v8uCsKGl8BQw/nk4juHcak/KHknKWCbiqLgIKacWEWDGa0v67QjG/AwkTWOVzTivCr+oMRPkO6wy3ZzeUSCBm21iese888fwV+vV1bEpJQ7Dm2ijGBhsmX3fSq+59s52OWrn14OVuCIghMKaspskJqlMuukgmXoygjrItj4Z2XyuwhwMH37blw==
  template:
    metadata:
      name: work-delegate-token
      namespace: harness-delegate-ng
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
spec:
  encryptedData:
    pgpassword: AgByfBrVlCaGrFgUVZ50GmW7PMMiKBC9tuGUK2t+2T9+MWAi72kACMwXeej5H5nFFoz1uZagmt3VVjOd5lcM+fVsWV1JDjcEbRpkxOnbCNIMEt8+JQfu3ovYGEFqER0I+ancBJp+Z0hfyKGRIDKw3HKQUbrWG7/Eu17BB1Fx8wqbeCd0Af1stFNwYmdj8SN7dwNzf80hoJPKDbwPsFV4vXt+KXAI2TVBLM1vczL17OTKRHTCVjZx9UAxmbvwWLMLNxJzFHTjQ7dvVDHnUwheAoH9bZGTJEL8OuJb+NjS+9uCuaXtuaY1aDatMASlE2uFAxqoum+GVw3RsY6KOh/hWkl85FuPbtSkDaWkkGOil7xO6g4u3wWwbZOvxHsMhNFjxxMQrwbHN2k7LyR7+4R3DMzhFvbB5dVXBg4EzVF8wvfNQTXJ4PnIwJ7a5TpaSE97JdxOPkSkO8qT3pqzWnCL547yw7MkH7c+YBqT0lVsvL8kOMKWeTd1ar6dQXA9yiTzcX2bBm76bzGTGFAOvyJrfdwjop1Oqwa2f05eNbBIY+If+5Xnp+tQzHGnN8GjxkNZWQ/QB+fTx6mpYVd42ndfhiwntTUOWbdzktu6h/pU7sbdZZj17c/BuTShJViYOc0WKx3Vfg/U1ow0LJ6SFqjNr98ycE9EvLfbtNkgVXY9wHwR2/N4uxRQagQQM/Ix9bt/W5RSZXj50IgFLfYmXztempCi0DuNDFxeRlmMpM0/dbBo8XEhdKx0j4G2
    tautullipassword: AgCS7dNntG5i8tbN7d/J28kW4EXeB7rA13v6Go4owXpFb62F5/LQCL/P0zaaO5iP0F26JiYExtE6O2CKzJo6iI5KfbnQ004VE9HoXFK4tn7IuuLx/MpMTqUysl4PwdqKw3wCHVR5f6CFj5w6mQIKzPpieBrCU7b7vGGgYWj9yNiCfMKo6R7NSUlaNHx2C1vqm9YH4ZrY4gVvgs76kf5AzmcwxPBr5RQez9QKZRVmU4vDECuH/r4uyGgO6a83vJpPnGn31yrfRHhTga0Jyz3LBHsesDSnAY2amDJhjo2/yNzA9wl+lVQCl9ykBB3cPdmYeDSNlWx6wCw8KeeAzzRLV/2z1X9GggAX0FthfraFWEtTW85YyLJdQgrwGDAKgzYjB158eqQrL124emzfNlAM4bkNmubv/Mi5TB6+sen0+dd1mXhFoSteewA9duwQVUQMcNHDZWNT2+70FBVQNyfJu6uXx23LOJtHj3rRa2CcK0jUqXPFutO21ZKi28sbk3TSnoUe6N0l+fomLanA8ir0n62iRgxQo8WTzH6WwFZXoj9fkiIy358SxsFGqlznmU0dHtEBCdB4/Y+i9cMwRdac1V1qpqIfH6m30d5B5Rf+8EOd+K5CjDvqZ7fKtBWhb3iUrk6VcnhzgMkxthnVcfm+R6rskrz7RR442pihNgEePLUgv/2EJbhZz92mQX+AapP/vDP3fUo17WaJAAkHZaTwILthoOUYXmuVfqGc7qUyb8op8A==
  template:
    metadata:
      name: survivor-tracker
      namespace: survivor-tracker
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgCrcc32jU7oDG3SX3Mhx0MhUjDyLXKn8WiWj7Q6liebsdQFFlenEx31EuAr7FtZQUWv6iDvYGF2dOMWhX5kJ26XieWM7cejuqHd4WoT8TX8QzuVWDrku98JCZeQnclKOHG7sZc+LoeqXxnw7jpQ3HkK+W1jZNg3SjHoupGvH3BO+IROxb/uy2+W1UIUYv8f9xqoeh/pFVre4XWNanlcIYjrKykkKCQKLnIwP49N7v3H7OESx0x8Ed4yGP3rOlSmQ52pRT7/Qvfw0PLEDAh1QPR1uOsoZPpE/sow3nLBjYRkSsl6rCh3u4EzmnmvAmGKGg+bIXzSHM0l8CsKT7lz6n1o14QiGaq0ZDvxZ9HaPpdcqvugtYpjGKgSfTbwwjXeN23T/hmjuXn1R8ABMcGMlYP4D3wLiZDxoOwAJWfVgd9mMzhU4z81oHwaKFG18ePbLJPT+XbtNBegTGeR4gm7GcdYFqgGukCnOjlmmjMgGfVdg42lU8tEy9hQUQi1TOAGAA2JqEsS0T3Y8/iKM5ifD/Vt9vmTNC4hZbWQPHrEQ3GTm/sDmbV9JgPrClmKWm9yj7Sy/yqYdgXjDpvDpEPISrjF6UmI5ig34y9USDFK+ya0klEnrOTCgXKwB4HRiTs6ao0r00S7Ba+w6ggPqxuKcNIVQUOZiziQoc0gFjEqsKNyZVIOQnw9WTlyI0J/ZixAwiKhe4+n2WFY8cfGswz0WUEmw6wAh9b5wnmwd1ViyoMyRbc2BpvUMTkwJas/e8YLFVthIUIB0yT1aDkGfuZoXW465tpxqRX2y0AkE3P9WAWovU4+M6Feh2LQ/hVanWSZwljqCxNWj+LGKpg62/Uk+q+fXnubMY7YT2UClwBfldT2OLTs08iCMk6xHhf2esnDkQCQ5LSqmxRK/0Bv4KWRTRPk26zLNuhJNDq8ld6VMeGyvLb46g==
  template:
    metadata:
      name: proxmox-cloud-controller-manager
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgBulYoCL8DrlAVd41yvceGPs5+ABOMlvJ4x8MdGIMh0qbgpM+afBVAfwO9vTC7Qu5SfhEJjVnKnjO7ZfIX1fL+4liAUs76HlcfxzmUSvCdCQ/iBdTAQhCDTc2lww9ehQ07BA2glEUXyLfj7XHXxjDy8rtBYa1sWCT9UFm22F8JLh6z9/YJdzt4gz/sGqL7sDvJbGhkJpsIG7FaTvz64Z8omVk0RlJgUeNe1Upmha3coGjMcUUhrbSZHelkRXnto3XDC3mPKy+jWg1i5vyCJzDU9rvICchiL0OxvNCOCF8k7QE5QZcMsAsGIjNy7hSLy11wcE9hfCg1d7pBt5vmcN726UFIjwPxi/t8PnRclpxKYmmGUVBgBfXldt0ycwY4/1lP0WFaa/cezJN2F4cJM+C6gN2oucyVsYZJmDRmBoHHoIEM+kFDK5YtIkA9+L2lw30fXr/EjWwMMFq7Yw8MRyMrbQ2qcNdXQaOgNFXcgDOrInchwPXsjMouS+TlBdxkwDI2NXJzxL8WBxCEN8rdJHYf0Wo+xnhpIJ/OPC4lBZCHgElbqTH3L5Mv9CureEkQwYcWGKcpkqFvg8uXVp5qjXQeSL0jhuH9Lf7aL4k2+Nc4BDnNjwhPWzXTIMdmcNndJ6mr+nTw9+Ey9t4+LNXjQR27BCUTHVH8W0BvJved9rxXtVhxfjXSrWOBAntjdf05WFYJU456L9SDNwGdoTioN9n7JVscIAYLujiTt7vOHPW7SdZYR8+LDObt2OqmgxZHCKfOIdT9jShzB4paXJuuvTNllMSwZTnng8hTw7jhzV4BTZNGIhbbhn0NBWfGD+nUrPxbKQYA4npUEK3QkhjggJzxwlUUP+xFeMib4ijr6nU2j9BsrxndCrHqWw5xWx6xgh70Y9osQJnDeajqMn95T1zDjroH8GO4lWw4Zoiqr50kL7D36Jl4VPC4=
  template:
    metadata:
      name: proxmox-csi
      namespace: csi-proxmox
    type: Opaque
