apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxmox-test
spec:
  storageClassName: proxmox
  volumeName: proxmox-test
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: 64Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      nodeName: jack
      containers:
      - name: home-assistant
        image: ubuntu
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - name: proxmox
          mountPath: /mnt/proxmox
      volumes:
      - name: proxmox
        persistentVolumeClaim:
          claimName: proxmox-test
