apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxmox-test
spec:
  storageClassName: proxmox
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: 64Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 1
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - name: proxmox
          mountPath: /mnt/proxmox
      volumes:
      - name: proxmox
        persistentVolumeClaim:
          claimName: postgres-15-isengard-postgres-15-0
