---
- name: Docker config
  hosts: cornelius
  become: yes
  tasks:
    
    - name: Install Python and python3-pip
      package:
        name:
          - python3
          - python3-pip
        state: present 

    - name: Install docker module for Python
      pip:
        name: 
          - docker
          - docker-compose

    - name: copy photoprism job file
      copy: 
        src: templates/photoprism.ini
        dest: /home/plex/appdata/photoprism/
        owner: plex

    - name: copy service file
      copy: 
        src: templates/plex_docker-compose.yml
        dest: /home/plex/docker-compose.yml
        owner: plex

    - name: Docker-compose up
      community.docker.docker_compose:
        project_src: /home/plex
        remove_orphans: true