apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  interval: 5m
  url: oci://ghcr.io/sergelogvinov/charts
  type: "oci"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: proxmox-cloud-controller-manager
      version: "0.2.24"
      sourceRef:
        kind: HelmRepository
        name: proxmox-cloud-controller-manager
      interval: 5m
  values:
    useDaemonSet: true
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
    existingConfigSecret: proxmox-cloud-controller-manager
